### ISSUE TITLE
Moving window to other monitor with Shift-Super-Left/Right/Up/Down does not detach window from tiling group

### ISSUE THREAD

**Issue by kassick** [Leleat/Tiling-Assistant#114]
**Describe the bug**

When a window is tiled, using gnome's default "Move window to monitor on ..." shortcuts (Shift-Super-arrow_keys) does not dettach the window from the tiling group.

As a result, keyboard navigation can select the original rectangle on the monitor the window was tiled to (now empty space). Selecting the phantom rectangle moves the focus to the window that was moved.

**Steps To Reproduce**

1. Add a shortcut for Tile Editing Mode
2. Connect an external monitor / second screen
3. Tile windows in one of the screens
4. Focus on one of the tiled windows, use Shift-Super-left/right/up/down to move it to some other monitor
5. Activate the shortcut for Tile Editing Mode in either the moved window or one of the other windows it was tiled with.
6. Navigate in some direction

Expected behaviour:
- The moved window is detached from the tiling group
- Activating Tile Editing Mode on the moved window should warn that the window is not tiled
- When using tile editing mode on on the windows of the group, selecting the empty space should 

- *When using Tile Editing Mode with the focus on the moved window*: Tile editing mode should not be activated as the window was moved outside of the screen it was originally tiled to
- *When using Tile Editing Mode with the focus on another of the tiled windows*: Moving the selection to the empy space should pop up the window selection widget.

**System Info:**
 - Distro: Fedora 34
 - GNOME (Shell) version: 40.6
 - Extension version: 27
 - XOrg/Wayland: Wayland 1.19.0

**Journalctl logs**

All other extensions disabled, no relevant output:
```
$  journalctl -fo cat /usr/bin/gnome-shell                                     
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
Ignoring excess values in shadow definition
libinput error: event21 - Keychron K8: client bug: event processing lagging behind by 11ms, your system is too slow
libinput error: event21 - Keychron K8: client bug: event processing lagging behind by 19ms, your system is too slow
libinput error: event21 - Keychron K8: client bug: event processing lagging behind by 25ms, your system is too slow

Ignoring length property that isn't a number at line 1, col 94
Ignoring length property that isn't a number at line 1, col 94
Ignoring length property that isn't a number at line 1, col 94
Ignoring length property that isn't a number at line 1, col 94
Ignoring length property that isn't a number at line 1, col 94
Ignoring length property that isn't a number at line 1, col 94
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Timelines with detached actors are not supported
Timelines with detached actors are not supported
Timelines with detached actors are not supported
```

**List of other extensions**
- AppIndicator and KSTatusNotifierItem Support
- Bluetooth quick connect
- Caffeine
- Dash to Dock
- Gnome 4x UI Improvements
- Impatiance
- No Overview at start-up
- Sound Input & Output Device Chooser
- Tiling Assistant
- User Themes
- windowNavigator

**Screenshots/-captures**
Can't capture screenshot while on tile editing mode :(

**Comment by Leleat** [comment]
Thanks for the detailed report!

> When using tile editing mode on on the windows of the group, selecting the empty space should

Sorry, I am not sure what you are trying to say here... should, what? Did you forget to finish it?

The rest I understand and will fix.

**Comment by Leleat** [comment]
On second thought, should the the tiled window restore its original size when moving to a new monitor or should it try to adapt to the new monitor size (e. g. take half of the new monitor size)?

**Comment by kassick** [comment]
IMHO it should restore it's original size.

Adapting the window size to the resolution of the monitor would go in line with "create a new tiling group on the other monitor", which might be unexpected from the user's point of view

On the other hand, gnome already tries do adapt the size and (native) tiling status -- so maybe there's no need to restore the size, just dettach from the tiling group and let gnome figure out the rest ...

**Comment by Leleat** [comment]
> IMHO it should restore it's original size.
>
> Adapting the window size to the resolution of the monitor would go in line with "create a new tiling group on the other monitor", which might be unexpected from the user's point of view

Alright, I go with that then. It's also the easier solution :)

**Comment by Leleat** [comment]
I pushed a new commit to `main`. This should fix this issue. Could you test it? If not, no problem, just let me know and I'll just directly upload the new version to EGO.

**Comment by Leleat** [comment]
PS.

Moving tiled windows across monitors doesn't work, if the size of the tiled window is way too big for the new monitor. A workaround is to untile the window before moving it to a new monitor. That's probably not something I can workaround as a GNOME Shell extension...
