### ISSUE TITLE
Port to Cinnamon

### ISSUE THREAD

**Issue by Alex-Bujorianu** [Leleat/Tiling-Assistant#115]
The title pretty much says it all. It would be really nice if you could port this extension to Cinnamon. I’m not sure exactly how much work it will involve, as I know Muffin has changed a bit compared to Mutter.

**Comment by Leleat** [comment]
> The title pretty much says it all. It would be really nice if you could port this extension to Cinnamon. I’m not sure exactly how much work it will involve, as I know Muffin has changed a bit compared to Mutter.

My extension also relies a bit on GNOME Shell and I am not familiar with Cinnamon at all so I don't know how easy the port would be. Since I don't use Cinnamon my motivation to do it isn't very high.

I'll leave this issue open in case someone else wants to do it...

**Comment by Leleat** [comment]
Closing this as I don't think it's likely to happen. I've now even hooked into GNOME Shells's altTab and plan to change the overview as well... so porting to Cinnamon probably doesn't seem realistic.
