### ISSUE TITLE
Configure split using arrow keys

### ISSUE THREAD

**Issue by Roy-Ermers** [Leleat/Tiling-Assistant#117]
right now when you tile windows you can't configure/move the split. I think this would be a helpful addition.
I would propose the following keybinds:
- `meta + shift + arrow-left`: move the split to the left
- `meta + shift + arrow-right`: move the split to the left

**Comment by Leleat** [comment]
> configure/move the split

Do you mean resizing the tiled windows so that the ratio of sizes between them is different?

**Comment by Roy-Ermers** [comment]
yes

**Comment by Leleat** [comment]
>> Do you mean resizing the tiled windows so that the ratio of sizes between them is different?
>
> yes

I see now, I am not gonna add that, however.

Adding **4** (left, right, top and bottom) more keyboard shortcuts just to resize windows doesn't seem like a good solution. There are already easily accessible ways to resize tiled windows. `Super` + `MMB` as a mouse-based resize mechanic. For keyboard-based resizing use the `Tile Editing Mode` (activated with 1 keyboard shortcut) and press `Super`+`Arrow keys`.
