### ISSUE TITLE
Middle-click raise/lower is broken

### ISSUE THREAD

**Issue by sej7278** [Leleat/Tiling-Assistant#120]
Middle-clicking an app's titlebar should raise/lower the window (on X11 although apparently not possible on Wayland) but this extension seems to inhibit that behaviour.

Debian Sid with Gnome 41.1

P.S. thanks for this extension, seems to be the only one that provides **mouse-based** quarter tiling.

**Comment by Leleat** [comment]
> Middle-clicking an app's titlebar should raise/lower the window

It should? I tried it with my extension disabled (and GNOME Shell restarted) and that behaviour doesn't happen. Did you enable add this behaviour with an extension or something?

In GNOME Tweaks there is a setting to make MMB lower a window (but not raise though). Is that what you are talking about?

**Comment by sej7278** [comment]
well i've no idea what happened there, but its working again now! no i don't have any other extensions installed, yes i did mean the mmb lower (not raise). closing thanks.

**Comment by Leleat** [comment]
> edit2: "raise together" setting turned off seems to fix that, not sure what the implications are.

If you tile a window and there is another tiled window visible (i. e. it's not covered by other windows), those windows will be considered in a Tile Group. If you have `Raise Together` enabled and you raise 1 window of a Tile Group, the other windows of that Tile Group will be raised to the foreground as well.

> right, its something to do with groups. if i create a layout like this, i can't lower the firefox window until i "unsnap" one of the right windows (there's a gedit window behind firefox) maybe that's expected behaviour?

Sorry, can't follow what you are saying there. Please elaborate (or maybe record your screen), if you feel like this is a bug based on my explanation of the 'Raise Together' setting.

**Comment by sej7278** [comment]
sorry i removed the screenshot, no its not a bug, disabling "raise together" reverted to the behaviour i was expecting.
