### ISSUE TITLE
Panel Indicator not available

### ISSUE THREAD

**Issue by wizziLalev** [Leleat/Tiling-Assistant#121]
New installation of EndeavourOS, minimal list of extensions added to keep the clutter low. Currently I cannot see the panel indicator that will allow me to chose layout. Also not seeing any way how to trigger usage of any layout.

**System Info:**
 - Distro: EndeavourOS - Arch based rolling release updated to latest versions 
 - GNOME (Shell) version: 41.1
 - Extension version: 27
 - XOrg/Wayland: Xorg

**List of other extensions**
Look at the screenshots

**Screenshots/-captures**
 - main issue
![Screenshot from 2021-12-06 03-18-51](https://user-images.githubusercontent.com/2341236/144773352-cdcea72c-b126-4c18-8d53-5d664ea1814e.png)

- list of extentions
![Screenshot from 2021-12-06 03-31-13](https://user-images.githubusercontent.com/2341236/144773410-511c739e-a24a-46f7-acab-d2634a93d87a.png)

**Comment by Leleat** [comment]
Uhh, guess you read the current User Guide 😅... the panel indicator is currently only in the `main` branch. For v27 of the extension there isn't a way to activate a layout with the mouse yet.

I'll push a new version of the extension to EGO in 1 or 2 weeks

**Comment by Leleat** [comment]
If you want to activate a layout with v27, you either directly need to asssign a keyboard shortcut to the layout or use the `Search a Layout` keyboard shortcut (a popup with a list of all layouts will appear).

If you want to mark a layout as a 'favorite layout', use the favorite button in the layouts preferences page. Then drag a window around while holding `Alt`.

Here is the Guide for v27

https://github.com/Leleat/Tiling-Assistant/blob/b6d287acb1f611888a9161ea0167d09bb79bf766/GUIDE.md

**Comment by wizziLalev** [comment]
Thanks @Leleat - that was quick sweat_smile . Will keep it mind and will wait for feature development to complete.

**Comment by Leleat** [comment]
Alright, closing this. New version is uploaded to EGO (but still needs to be reviewed).
