### ISSUE TITLE
Wayland/GNOME crash on closing tiled window

### ISSUE THREAD

**Issue by Masqueey** [Leleat/Tiling-Assistant#124]
When I have a few windows open and use `Super + 6` to tile one to the right, I get the option which window I would want to tile to the left. If I pick one with `Enter`, it sets it to the other half of the screen as expected. When I then close this additional window, GNOME crashes. I just installed the plugin so it could be I still need to configure something. The "App Switcher and Tiling Popup" toggle did not change anything, it crashes both when it's on or off.

Sorry for the little information. If there is more debugging I can do or information I can provide, please let me know.

**Comment by Leleat** [comment]
Thanks, I'll try to reproduce this.

**Comment by Leleat** [comment]
I did a fresh install of my extension and tried to to reproduce this with Fedora 35 (Wayland) but GNOME Shell didn't crash for me. So I need some more info:

- Distro (incl. version)
- GNOME (Shell) version
- Extension version
- List of other extensions
- Do you see anything in `Journalctl logs` when reproducing the crash?

**Comment by Masqueey** [comment]
**It has to do with the second monitor.** It does not happen when I use my primary screen. If I press `Super + 6` and add the second window, then close either one, it works fine. Doing this on my secondary screen causes it to crash.

My primary screen has the GNOME top bar and the Activities button, the secondary does not.

**Comment by Leleat** [comment]
> ```g_signal_handler_block: assertion 'handler_id > 0' failed
>
>ANOM_ABEND auid=1000 uid=1000 gid=1001 ses=6 subj==unconfined pid=96164 comm="gnome-shell" exe="/usr/bin/gnome-shell" sig=11 res=1
>
>JS ERROR: TypeError: raisedWindowsTileGroup is undefined
>updateTileGroup/</raiseId<@/home/max/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js:297:21
>updateTileGroup/</raiseId<@/home/max/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js:320:34
>untile@/home/max/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js:207:16
>_onWorkspaceChanged@/home/max/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js:899:18
>updateTileGroup/</wsId<@/home/max/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js:286:73
>
>g_signal_handler_unblock: assertion 'handler_id > 0' failed
>
>segfault at 18 ip 00007ff61999828f sp 00007ffcf278efe0 error 4 in libmutter-9.so.0.0.0[7ff6198f3000+17a000]
>
>Process 96164 (gnome-shell) of user 1000 dumped core.
>```

> It has to do with the second monitor. It does not happen when I try this on my primary screen or when I unplug the second monitor. If I then perform the previously described steps, it works as expected. If I try the same thing on my secondary screen, it crashes.
>
> My primary screen has the GNOME top bar and the Activities button, the secondary does not. Both screens have the same number of pixels and ratios, the secondary screen is a lot larger.

That's very helpful, thanks! I hopefully can fix it fairly quickly with that info.

**Comment by Leleat** [comment]
Alright, pushed a commit, which fixes the crash. I'll upload it to EGO now.
