### ISSUE TITLE
Windows think they're floating even after snapping

### ISSUE THREAD

**Issue by HonbraDev** [Leleat/Tiling-Assistant#127]
**Describe the bug**

When I snap a window to the edge of the screen, the window retains rounded corners. Firefox also doesn't hide the "corner grabbing space".

**Steps To Reproduce**

Snap a window to the edge of the screen.

**System Info:**
 - Distro (incl. version): Ubuntu 21.10
 - GNOME (Shell) version: 40.4.0
 - Extension version: 31
 - XOrg/Wayland: Wayland

**Journalctl logs**

```
Skipping parental controls support as it’s disabled
Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
Will monitor session 12
g_strsplit: assertion 'string != NULL' failed
Telepathy is not available, chat integration will be disabled.
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
GNOME Shell started at Thu Dec 16 2021 12:08:05 GMT+0100 (CET)
Registering session with GDM
Received error from D-Bus search provider com.github.bilelmoussaoui.Authenticator.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.github.bilelmoussaoui.Authenticator.SearchProvider was not provided by any .service files
Received error from D-Bus search provider com.github.bilelmoussaoui.Authenticator.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.github.bilelmoussaoui.Authenticator.SearchProvider was not provided by any .service files
Error in size change accounting.
Error in size change accounting.
^C
```

**List of other extensions**

```
tiling-assistant@leleat-on-github
```

**Screenshots/-captures**

With the extension:
![With the extension](https://user-images.githubusercontent.com/54026315/146361278-eb1a85a2-6539-4737-b533-44f54739e9bf.png)

Without the extension (had to snap again):
![Without the extension](https://user-images.githubusercontent.com/54026315/146361429-fb67973a-82a6-4819-98f6-985f2d342731.png)

**Comment by Leleat** [comment]
I don't think I could 'fix' this. 'GNOME's native tiling doesn't happen in GNOME Shell, so I can't really change or imiate it with a GNOME Shell extension. All my extension and all other tiling extensions do is place and resize floating windows to _fake_ tiling... so I am closing this issue since I don't consider this a bug.
