### ISSUE TITLE
Override GNOME's default super+left/right

### ISSUE THREAD

**Issue by Leleat** [Leleat/Tiling-Assistant#133]
### Discussed in https://github.com/Leleat/Tiling-Assistant/discussions/130

<div type='discussions-op-text'>

<sup>Originally posted by **sxc731** December 30, 2021</sup>
Would it be possible for Tiling-Assistant to take over the standard super+left/right GNOME keybindings, so long as the user disables them in the GNOME keyboard shortcut settings?  I feel this would greatly increase TA's usability; particularly when using it on laptops, which often don't feature numpads.</div>

**Comment by allenmcbride** [comment]
It sounds like this change was meant to restore the native Gnome keybindings; is that right? I just upgraded Tiling Assistant, and for me at least, the new version seems to have disabled the default Gnome keybindings instead, without replacing them. I restored the defaults in Gnome settings, and now they work again, alongside the Tiling Assistant bindings. So there's no problem for me, but I thought I'd mention it in case there's something unexpected going on.

**Comment by Leleat** [comment]
> It sounds like this change was meant to restore the native Gnome keybindings; is that right? I just upgraded Tiling Assistant, and for me at least, the new version seems to have disabled the default Gnome keybindings instead, without replacing them. I restored the defaults in Gnome settings, and now they work again, alongside the Tiling Assistant bindings. So there's no problem for me, but I thought I'd mention it in case there's something unexpected going on.

Previously, the default shortcuts for Tiling Assistant were `Super + Numpad`. But the newest version changed Tiling Asisstant's shortcuts to replace GNOME's default shortcuts. So I disabled GNOME's native tiling shortcuts.

Currently, I always override GNOME's native tiling shortcuts when the extension is enabled (e. g. on every boot, screen unlock...). That's a bug which I will fix in the next version. 

If you don't like Tiling Assistant to override GNOME's shortcut open `/home/timmy/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/extension.js` and delete the lines 72-87 (both lines included) and reload GNOME Shell for the change to take effect.

**Comment by parcelcat** [comment]
@Leleat The mutter/gtk bug described in #138 causes the "Tile to Left" and "Tile to Right" features to break in Tiling Assistant, but GNOME's native "View split on left" and "View split on right" features still work properly. To have a functional left/right tiling feature, I must disable the keybindings in Tiling Assistant and re-enable them in GNOME. I don't mind doing this one time, but Tiling Assistant disables the GNOME keybindings every time I log in, which is very inconvenient for me.

Would it be possible to roll back this change and re-implement it after the mutter/gtk bug is fixed, or alternatively make the overrides optional? I feel like override shouldn't be the default behavior, since it exacerbates an existing bug that makes left/right tiling unpleasant to use.

**Comment by Leleat** [comment]
Hmm, I've got a notification about someone leaving a message here but I don't see it now 🤔... maybe deleted?.

Anyway, if you are affected by the GNOME bug under Wayland you can just disable Tiling Assistant since that bug basically interferes with all features and wait for the next version of Tiling Assistant with a fix. That way the shortcuts won't be overriden in the meantime.

**Comment by allenmcbride** [comment]
Thanks for your earlier response! And yes, I think someone else posted and then deleted it. At any rate, I think I understand now that what's supposed to happen is for Tiling Assistant to disable the GNOME keybindings but replace them with identical keybindings. For me, it's disabling the GNOME bindings but replacing them with the old Super+Numpad keys. I guess the upgrade successfully made the disabling happen but didn't successfully change Tiling Assistant's bindings. It's not a big deal to me, and of course I can edit the Tiling Assistant bindings myself; I just write this to clarify what's happening in case it's helpful.

**Comment by freeseek** [comment]
I have this same exact issue with Tiling-Assistant v54 and Ubuntu 26.04. To avoid the conflict between Mutter and Tiling-Assistant I used these commands:
```
gsettings set org.gnome.mutter.keybindings toggle-tiled-left "[]"
gsettings set org.gnome.mutter.keybindings toggle-tiled-right "[]"
```
This was only Tiling-Assistant reacts when I press <Super>+Left and <Super>+Right, restoring the desired behavior
