### ISSUE TITLE
Maximized gapped window and restore window doesn't work at the same time 

### ISSUE THREAD

**Issue by BerkayOrhan** [Leleat/Tiling-Assistant#135]
I was both using gaps on maximized windows and overwritten gnome shortcuts. Super+left/right and also without gaps super+up works as intended, they restore their sizes. However, as i said in title, enabling gaps messes with extension. I think it could be about window's state. Still using super+up again works just fine so its not a big deal. Thank you for this great extension.

 - Distro (incl. version): Ubuntu 21.10
 - GNOME (Shell) version: 40
 - Extension version: 32
 - XOrg/Wayland: Xorg

**Comment by Leleat** [comment]
Thanks for the report! Fixed with the latest commit.
