### ISSUE TITLE
"Light Bulb" menu options cause runaway process & memory leak

### ISSUE THREAD

**Issue by jason-bxtn** [Leleat/Tiling-Assistant#136]
**Describe the bug**
***When using the extension's Settings "Light Bulb" menu, 4 of the 5 options do not work correctly.***

* Clicking "Report a Bug", "User Guide", or "License" results in a runaway process `gls` which locks one processor at 100% usage and also creates a memory leak, where the process continues to allocate memory until it is ended.
* Clicking "Changelog" works as it should.
* Clicking "Advanced..." appears to do nothing at all.

**Steps To Reproduce**
1. Open the Gnome "Extensions" app.
2. Click the "Gear" Settings icon for Tiling Assistant.
3. Click the "Light Bulb" button in the upper-left corner of the screen.
4. Click any of the options from the menu that appears to get the results reported above.

**System Info:**
 - Distro (incl. version): Fedora Workstation 35
 - GNOME (Shell) version: 41.2
 - Extension version: 31
 - XOrg/Wayland: Wayland

**Journalctl logs**
ATK Bridge is disabled but a11y has already been enabled.
Object St.Bin (0x56370c31a0a0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x5637090f51d0 ==
#0   7fffd2936c10 b   resource:///org/gnome/shell/ui/workspaceThumbnail.js:1410 (3ca140783dd0 @ 17)
== Stack trace for context 0x5637090f51d0 ==
#0   7fffd2936c10 b   resource:///org/gnome/shell/ui/workspaceThumbnail.js:1410 (3ca140783dd0 @ 17)
Object St.Bin (0x563709539030), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Timelines with detached actors are not supported
Timelines with detached actors are not supported
_Note: All of the above entries were already logged before I reproduced the issue - once the issue was triggered, no additional log entries were triggered._

**List of other extensions**
I disabled all installed extensions and restarted my computer to make certain no extension conflicts were the cause of this issue.

**Screenshots/-captures**
https://imgur.com/a/1sAXoZG

**Comment by Leleat** [comment]
Thanks for the report, I'll take a look.

> Clicking "Advanced..." appears to do nothing at all.

It should give you access to a new settings page. It will appear to the right of the `Keybindings` page.

**Comment by jason-bxtn** [comment]
Thanks for the quick reply.

> It should give you access to a new settings page. It will appear to the right of the `Keybindings` page.

This does work as expected - I was so focused on capturing all of the other details that I never noticed the new settings page appearing.

**Comment by Leleat** [comment]
I can only reproduce this on Wayland. And tbh, I don't know, if this is really 'my' bug. I simply use a 1 function from a GNOME library to open the default handler for my github URL I see that other extensions, which use similiar methods like `just perfection` also suffer from this bug.

I'll try looking for a workaround. If you want know what those 3 menu items (Report a Bug, User Guide, or License) do: they just open a link to the following locations:

https://github.com/Leleat/Tiling-Assistant/issues
https://github.com/Leleat/Tiling-Assistant/blob/main/LICENSE
https://github.com/Leleat/Tiling-Assistant/blob/main/GUIDE.md

**Comment by jason-bxtn** [comment]
Thank you for the response. I only noticed this because I wanted to report a bug about something else (which I will be doing shortly) - I certainly wasn't aware of the inner workings of extensions and that others seem to have the same issue because of a GNOME library. I will investigate reporting this upstream to GNOME.

**Comment by Leleat** [comment]
> I will investigate reporting this upstream to GNOME.

Don't worry about that. I plan to do that already.

**Comment by Leleat** [comment]
fixed in 591f4ad
