### ISSUE TITLE
[Feature Request] Different screen edge margins for left, right, top, bottom

### ISSUE THREAD

**Issue by Austint30** [Leleat/Tiling-Assistant#146]
This extension has gotten me almost what I want, but not quite without the ability to have different screen edge margins for the top, bottom, left, and right of the screen.
In my case I want to give a large margin at the bottom of the screen for dash-to-dock, and a small margin on the top, left, and right edges of the screen. Currently in order to do this I have to turn off intellihide in the dock's settings so the window doesn't cover it. However, I want a window to fully cover the dock when I press the maximize button, so turning off intellihide doesn't really work here.

My Gnome Version: 40

**Comment by sej7278** [comment]
makes sense - could possibly help with the difficulty i'm having of dragging to the right screen edge of my primary monitor just causing the window to move the the secondary monitor instead of triggering a half-tile.

**Comment by Leleat** [comment]
I am not opposed to this idea but tbh it would be super low on my todo list because I don't see that much value in it. So ideally someone else implements this and I'll merge it...

**Comment by Leleat** [comment]
Implemented by @[CharlieQLe](https://github.com/CharlieQLe). So closing this.
