### ISSUE TITLE
Multi-Monitor bug - wrong height?

### ISSUE THREAD

**Issue by edent** [Leleat/Tiling-Assistant#150]
**Describe the bug**
I have two monitors. A vertical and a horizontal one. When I tile at the top of the vertical monitor, the extension places the window at the top of the horizontal window's height.  This is hard to explain!

**Steps To Reproduce**

Here's my monitor set up:
<img src="https://user-images.githubusercontent.com/837136/158151266-f039ac0c-7b8a-4601-a1f8-e458c398f2c0.png" height="200"/>

If I drag a window to the top of the vertical monitor, wait for the extension to go to "top half" mode, this is what I end up with:
<img src="https://user-images.githubusercontent.com/837136/158151788-14e260fb-18d9-4b05-9004-ccc5cba20d1b.png" height=400 />

If I use "quarter tiling", it gets placed at the correct height.  Same for left/right tiling. Bottom tiling also works. Literally just top half tiling which has the issue.

**System Info:**
 - Distro (incl. version): Pop_OS 21.10
 - GNOME (Shell) version: 40.4.0
 - Extension version and from where (e. g. EGO, `main` branch...): Main from https://extensions.gnome.org/extension/3733/tiling-assistant/
 - XOrg/Wayland: Wayland

**Comment by MrReSc** [comment]
I'm facing exactly the same bug,

**Comment by edent** [comment]
Ah! I think I've found the problem.

If I start an app on my laptop's screen, then drag it to the top of my external monitor, it only goes as high as the laptop's screen.

If I drag it to the external monitor, then release, *then* drag to the top, it goes to the correct height!

I can't reproduce it consistently, but I **think** that's the cause of the issue.

**Comment by Leleat** [comment]
Sorry for the late response.


> If I drag it to the external monitor, then release, then drag to the top, it goes to the correct height!

That might be helpful. Can you try to manually edit the file in `~/local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js` and change 

```
window.move_resize_frame(false, x, y, width, height);
```
in the `tile` function  to

```
window.move_resize_frame(true, x, y, width, height);
```

It should be in line 187 if you use the current `main` (i. e. GNOME 42) branch. If you are on older GNOME/extension versions it should be around line 210.

Afterwards please reload GNOME Shell and see, if the issue still occurs.

**Comment by Leleat** [comment]
Closing this. I think it had the same underlying issue as #137. Hopefully, the latest commit fixes it.
