### ISSUE TITLE
Any plan to support Gnome 42?

### ISSUE THREAD

**Issue by laichiaheng** [Leleat/Tiling-Assistant#154]
**Describe the bug**
It is not compact with Gnome 42
**Steps To Reproduce**
Upgrade to Gnome 42
**System Info:**
 - Distro (incl. version): Arch Linux
 - GNOME (Shell) version: 42.0
 - Extension version and from where (e. g. EGO, `main` branch...): 32
 - XOrg/Wayland: Wayland

**Journalctl logs**

**Comment by Leleat** [comment]
Yeah, I plan to add support for it in the next few weeks (hopefully the upcoming week). Closing this since there is already a different issue for 42 support.
