### ISSUE TITLE
Tile Assistant ctrl+drag not working

### ISSUE THREAD

**Issue by b26** [Leleat/Tiling-Assistant#158]
**Describe the bug**

**Steps To Reproduce**

**System Info:**
 - Distro (incl. version): `Ubuntu 20.04.4 LTS`
 - GNOME (Shell) version: `3.36.8`
 - Extension version and from where (e. g. EGO, `main` branch...): `23` downloaded from [extentions.gnome.org](https://extensions.gnome.org/extension/3733/tiling-assistant/)
 - XOrg/Wayland: `X11`

**Journalctl logs**

Having issues using Tile Assistant. The ctrl + drag feature isnt' working for me. It's also not highlighting anything as shown in https://github.com/Leleat/Tiling-Assistant/blob/main/media/ReadMe_Preview.gif

Is there a specific setting that I need to turn on? 

![image](https://user-images.githubusercontent.com/2287343/164029268-a7619aee-ed70-48e3-98ba-7ddc2e06b286.png)

![image](https://user-images.githubusercontent.com/2287343/164029327-2465e0c2-2465-4b3d-925b-507b267a456c.png)

![image](https://user-images.githubusercontent.com/2287343/164029376-2b407b8b-82a0-41ff-a6ed-e7b6bf93d763.png)

![image](https://user-images.githubusercontent.com/2287343/164047843-ad626d76-312f-422e-929e-0621c2bb7b3e.png)

> @b26 please open a new issue with more info (like the extension version, distro etc... basically just fill out the template) since this doesn't look related to the original issue/suggestion. Also; do you mean https://github.com/Leleat/Tiling-Assistant/blob/main/GUIDE.md#Adaptive-Tiling= with 'ctrl-drag'?

Yes that is correct, currently having issues with Adaptive-Tiling.

Thank you very much

**Comment by Leleat** [comment]
Ctrl-Drag only works, if you have existing windows tiled. Is that the case? E.g. did you drag a window to a screen edge and then started to try to ctrl-drag a different window?

If yes, please type `journalctl -f -o cat /usr/bin/gnome-shell` into a terminal and try it again. Are there any error messages in the terminal? If so, please post them here.

**Comment by b26** [comment]
> Ctrl-Drag only works, if you have existing windows tiled. Is that the case? E.g. did you drag a window to a screen edge and then started to try to ctrl-drag a different window?

I tried dragging my window to a screen edge and pressing ctrl+drag. Not sure what you mean by different window? Do you mean a different screen or different monitor? Having said that, I did drag it to a screen edge and pressed ctrl+drag during testing

---- 

> If yes, please type journalctl -f -o cat /usr/bin/gnome-shell into a terminal and try it again. Are there any error messages in the terminal? If so, please post them here.

```
➜  ~ journalctl -f -o cat /usr/bin/gnome-shell
Received error from D-Bus search provider org.gnome.seahorse.Application.desktop during GetResultMetas: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.gnome.Shell.SearchProvider2” on object at path /org/gnome/seahorse/Application
Wrong number of result metas returned by search provider org.gnome.seahorse.Application.desktop: expected 1 but got 0
Slack1, Impossible to lookup icon for 'Slack1_2-panel' in path /run/user/1000/snap.slack/.org.chromium.Chromium.SkRmnb
unable to update icon for Slack1
Slack1, Impossible to lookup icon for 'Slack1_2-panel' in path /run/user/1000/snap.slack/.org.chromium.Chromium.SkRmnb
unable to update icon for Slack1
Received error from D-Bus search provider org.gnome.seahorse.Application.desktop during GetResultMetas: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.gnome.Shell.SearchProvider2” on object at path /org/gnome/seahorse/Application
Wrong number of result metas returned by search provider org.gnome.seahorse.Application.desktop: expected 1 but got 0
Received error from D-Bus search provider org.gnome.seahorse.Application.desktop during GetResultMetas: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.gnome.Shell.SearchProvider2” on object at path /org/gnome/seahorse/Application
Wrong number of result metas returned by search provider org.gnome.seahorse.Application.desktop: expected 1 but got 0
Received error from D-Bus search provider org.gnome.seahorse.Application.desktop during GetResultMetas: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.gnome.Shell.SearchProvider2” on object at path /org/gnome/seahorse/Application
Wrong number of result metas returned by search provider org.gnome.seahorse.Application.desktop: expected 1 but got 0
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4000007
```

**Comment by Leleat** [comment]
> I tried dragging my window to a screen edge and pressing ctrl+drag. Not sure what you mean by different window? Do you mean a different screen or different monitor? Having said that, I did drag it to a screen edge and pressed ctrl+drag during testing

Ctrl-Dragging a window only works, if there are **other** tiled windows visible on screen. E.g. 
1. Drag Window A to the left screen edge and let go -> the window will tile to the left half
2. Drag Window B while holding Ctrl

Here is an example of the 'adaptive tiling' in action https://raw.githubusercontent.com/Leleat/Tiling-Assistant/main/media/Guide_AdaptiveTiling.mp4.

With that being said; you are on an older extension version. I am not sure, if I already added that feature at that point. So if it doesn't work for you, I need to check at what point I've added that feature.

**Comment by Leleat** [comment]
Any news here with this:

> Ctrl-Dragging a window only works, if there are **other** tiled windows visible on screen. E.g.
>
>    Drag Window A to the left screen edge and let go -> the window will tile to the left half
>    Drag Window B while holding Ctrl
>
>Here is an example of the 'adaptive tiling' in action https://raw.githubusercontent.com/Leleat/Tiling-Assistant/main/media/Guide_AdaptiveTiling.mp4.

Does it still not work?

**Comment by b26** [comment]
Got it working - I upgraded my GNOME shell and once I did that it started working properly. 

Thanks for the great app. It really helps. 

Cheers again
