### ISSUE TITLE
Gnome 41, Wayland - Windows resize after suspend or any display off

### ISSUE THREAD

**Issue by MindlessDreams** [Leleat/Tiling-Assistant#163]
Hello, Ive been trying all options but no luck. I just need quarter tilling so I disable all other options. It works fine under X11, but under Wayland most apps lose their positions and resize after display is off or suspend. Any advise on the settings? I tried "Grab End" option - it does not make a diff. BTW I noticed that even without the extension - if the app windows are not snapped left or right and left as they open on launch - they usually resize and move. Is this Wayland issue in general? Any advice appreciated, thank you for the great extension!

**Comment by Leleat** [comment]
My (and other tiling) extension only do(es) 'fake tiling' by moving and resizing windows to make it look like tiling. But if 'floating' windows get moved/resized for you after a suspend, there is nothing I can do from the perspective of an extension/gnome shell. Problem might be in mutter or something...

Other people reported similiar problems already in mutter. See for example https://gitlab.gnome.org/GNOME/mutter/-/issues?scope=all&state=opened&search=suspend+window

Anyway, there is nothing I can do about it, sorry... so closing this.

**Comment by MindlessDreams** [comment]
Thank you for taking the time to respond to my question. My problem is than the windows "tiled" with the extension get resized after  suspend, not the "floating" on. And it seems to does it only under Wayland. Thanks!

**Comment by Leleat** [comment]
> My problem is than the windows "tiled" with the extension get resized after suspend, not the "floating" on. 

Sorry, not sure I understand what you said there. Didn't you say here that it also happens with normal windows, if my extension is disabled? 

> BTW I noticed that even without the extension - if the app windows are not snapped left or right and left as they open on launch - they usually resize and move

**Comment by MindlessDreams** [comment]
Hello, yes, this is correct - not snapped windows with the extension disabled tend to resize after suspend. All snapped windows retain position and size (again with extension disabled). My problem is that with extension enabled - all windows - tiled and not tiled via the extension lose their position and size after display off or suspend.

**Comment by MindlessDreams** [comment]
Hello, just wanted to share some more observations on my issue. It turns out this is valid ONLY for firefox, thunderbird and librewolf (firefox clone) - either flatpak or rpm...All other programs I use behave as expected with your extension. Further more under gnome 42 (fedora 36) the problematic firefox, thunderbird and librewolf do not resize on screen off - they retain position and work as they should BUT there is another issue - after screen off they can not open new windows. So the issue is with them - unfortunately I am unable to figure it out for now. Thanks for the great extension.

**Comment by aral** [comment]
@MindlessDreams I’m seeing similar behaviour on Fedora Silverblue 36 (GNOME 42; Wayland).

GNOME Console and Firefox (at least), resize after a suspend.

In order to get the correct size/position back, if I remember correctly, all I have to do is click on GNOME Console. However, with Firefox, I have to untile and retile it.

I do not experience the window position loss issue with floating windows when this plugin is disabled/not present.

**Comment by Leleat** [comment]
@aral 

Try and see if you can reproduce the issue with my extension disabled while moving a window with looking glass.

1. focus a window, which you have issues when using my extension with
2. open looking glass (`Alt`+`F2` then enter `lg`)
3. Enter `global.display.get_tab_list(Meta.TabList.NORMAL_ALL, null)[0].move_resize_frame(true, 100, 100, 500, 500)` (the window should be moved to the top left with some gaps)
4. close looking glass with `Esc`
5. Try to suspend and see if issue still happens

If it does, there is probably nothing I can do. You should open an issue in mutter and hope it gets fixed there. There may be similiar issues already opened (https://gitlab.gnome.org/GNOME/mutter/-/issues?scope=all&state=opened&search=suspend+window)
