### ISSUE TITLE
Can't install - Failed to execute child process “msgfmt” (No such file or directory)

### ISSUE THREAD

**Issue by jmobley0429** [Leleat/Tiling-Assistant#165]
On attempt to install, in relatively fresh install of Ubuntu 21.10, running commands:
```
sh ./scripts/build.sh -i
Packaging extension...
```
Error message:
```
(gnome-extensions pack:101662): GLib-GIO-CRITICAL **: 03:31:54.765: g_subprocess_wait: assertion 'G_IS_SUBPROCESS (subprocess)' failed
Failed to execute child process “msgfmt” (No such file or directory)
```

Able to resolve by running `sudo apt install gettext`

After that the install works fine.

**Comment by Leleat** [comment]
`main` only supports the latest GNOME Shell version. (I guess I need to update the readme). If you are on older GNOME Shell versions you should install it from EGO.
