### ISSUE TITLE
Alt+dragging windows to the edge does not trigger tiling

### ISSUE THREAD

**Issue by dmalyuta** [Leleat/Tiling-Assistant#172]
**Describe the bug**

Most times I use the `Alt` window action key in order to click and drag a window, instead of dragging the window by clicking on its title bar. It appears that Alt-dragging a window to the edge does not trigger tiling (whereas dragging using the title bar does). Animation shown below.

![tiling-extension-no-alt](https://user-images.githubusercontent.com/12475811/168502541-947885f2-2374-4ebe-9e36-141e2e19c4cd.gif)

**System Info:**
 - Distro (incl. version): Ubuntu 22.04
 - GNOME (Shell) version: 42
 - Extension version and from where (e. g. EGO, `main` branch...): `main` branch
 - XOrg/Wayland: XOrg

**Journalctl logs**

**Comment by Henry78** [comment]
I face the same issue. When switching the windows action key to <ctrl> tiling is triggered again.

**Comment by Henry78** [comment]
This is somehow still an issue here with `Alt` as window action key.

I checked `/org.gnome.shell.extensions.tiling-assistant.gschema.xml` and found the mod key properly(?) set to "2", but only dragging the title bar to the edge offers tiling, not dragging the window with Alt+Click.

Tiling suggestion when dragging the window to the border works, if I switch to `Super` as window action key.

Observation: Regardless of the setting of the window action key, the gschema file always lists `2` in `adaptive-tiling-mod` and `move-favorite-layout-mod`, even after enabling/disabling the extension and login/logout.

```sh
$ dconf read /org/gnome/desktop/wm/preferences/mouse-button-modifier
'<Alt>'
$ grep -E -A2 "tiling-mod|layout-mod" org.gnome.shell.extensions.tiling-assistant.gschema.xml 
		<key name="move-adaptive-tiling-mod" type="i">
			<!-- 0: Disabled, 1: Ctrl, 2: Alt, 3: RMB, 4: Meta -->
			<default>2</default>
--
		<key name="move-favorite-layout-mod" type="i">
			<!-- 0: Disabled, 1: Ctrl, 2: Alt, 3: RMB, 4: Meta -->
			<default>2</default>   

# Switch to Super as window action key using gnome-tweaks
$ dconf read /org/gnome/desktop/wm/preferences/mouse-button-modifier
'<Super>'
$ grep -E -A2 "tiling-mod|layout-mod" org.gnome.shell.extensions.tiling-assistant.gschema.xml 
		<key name="move-adaptive-tiling-mod" type="i">
			<!-- 0: Disabled, 1: Ctrl, 2: Alt, 3: RMB, 4: Meta -->
			<default>2</default>
--
		<key name="move-favorite-layout-mod" type="i">
			<!-- 0: Disabled, 1: Ctrl, 2: Alt, 3: RMB, 4: Meta -->
			<default>2</default>                                              
```

**Comment by Leleat** [comment]
@Henry78 the schema.xml only tells you the default values but not the actual current set value of the setting. You can get their value with  dconf/gsettings at `/org/gnome/shell/extensions/tiling-assistant/`. I suspect one of the mod key settings has the value 3 (`Alt`). You can also use the GUI prefs window to see the current window. You need to enable the advanced/experimental settings to see them (use the button in the headerbar of the extension's preferences). If that's the case, you need to set it to a different value like 4/`Meta`.

PS. One thing is weird in your output though. `move-adaptive-tiling-mod` and `move-favorite-layout-mod` should have different default values. See https://github.com/Leleat/Tiling-Assistant/blob/main/tiling-assistant%40leleat-on-github/schemas/org.gnome.shell.extensions.tiling-assistant.gschema.xml#L244. No idea what is going there...
