### ISSUE TITLE
[Multi-monitor][Layouts] Workspace origin is incorrect on secondary screen

### ISSUE THREAD

**Issue by szszoke** [Leleat/Tiling-Assistant#174]
**Describe the bug**

I have a multi-monitor setup with two 27 inch screens running at 2560x1440. The primary screen is in landscape orientation, the secondary screen is in portrait. They are positioned in a "T" shape that is rotated 90 degrees.

I am using a layout that splits the secondary screen in three.

If I drag a window to the top row on the secondary screen, the preview shows correctly where the window would be placed, but if I let go of the mouse button then the window is placed incorrectly. The width and height seems to be correct but there is a gap on top of the window. The gap seems to be exactly as big as the vertical offset between my two screens + the height of the top bar on Gnome  Shell.

If I align the top of my screens in Gnome Settings then the gap is only as big as the height of the top bar of Gnome Shell.

The issue is still there if I restart my system but if I then turn off an on the extension via the `Extensions` app then it seems to disappear.

**Steps To Reproduce**
1. Enable layouts
2. Add a layout with three rows
   * 0--0--1--0.33
   * 0--0.33--1--0.33
   * 0--0.66--1--0.33
3. Enable layout on the portrait screen
4. Move a window while holding ALT

**System Info:**
 - Distro (incl. version): Manjaro Gnome 21.2.6
 - GNOME (Shell) version: 42.1
 - Extension version and from where (e. g. EGO, `main` branch...): 33 from https://extensions.gnome.org/extension/3733/tiling-assistant/
 - XOrg/Wayland: Wayland

**Journalctl logs**

No logs printed

**Comment by Leleat** [comment]
Can you try the `main` branch and see if the issue still persists? Alternatively, please just apply [this commit](https://github.com/Leleat/Tiling-Assistant/commit/1e4176a9a7037ee5dd0612e4c9f9dbe45d4e67cf) and see if it fixes your issue. Don't forget to reload GNOME Shell after installing the new version/manually editing the file.

**Comment by Leleat** [comment]
> Can you try the main branch and see if the issue still persists? Alternatively, please just apply [this commit](https://github.com/Leleat/Tiling-Assistant/commit/1e4176a9a7037ee5dd0612e4c9f9dbe45d4e67cf) and see if it fixes your issue. Don't forget to reload GNOME Shell after installing the new version/manually editing the file.

Since you responded in the other issue and I think it was the same bug, I am gonna close this. If the current `main` branch doesn't fix this bug, feel free to comment here again.

**Comment by szszoke** [comment]
I tested the current `main` branch and it seem to have solved the issue. I will keep using it for a while and see if something else pops up. Thanks!
