### ISSUE TITLE
[Layouts] Window spanning across two layout rectangles

### ISSUE THREAD

**Issue by szszoke** [Leleat/Tiling-Assistant#178]
I am wondering if there are any plans to support windows spanning across two layout rectangles. In my case I have a screen that is in portrait orientation and I have it split up into three rows with a Favorite Layout. I use the mouse and the ALT key to snap windows into one of the three rows.

What I would like to do is to be able to snap a window into two adjacent rows. An example implementation could be FancyZones from Microsoft PowerToys where this functionality exists (and where I used it for the first time). With FancyZones, when a window is being dragged close to where two "fancy zones" join, the window can be snapped across both.

I suppose this could work for simple row/column based layouts but could end up complicated when the layout grid is more complex.

In order to support the simpler use case the logic could be that if the window is dragged near the horizontal joint of two neighboring layout rectangles then the two rectangles need to have the same width in order for the window to span across both. The same logic would apply for the vertical joints as well but in that case the height of the rectangles must be the same.

What do you think about this?

**Comment by Leleat** [comment]
This already exists (although slightly different than in FancyZones). You can hold `Super` while dragging a window and the preview will span multiple rectangles based on when you starting holding `Super`.
