### ISSUE TITLE
Option to disable snapping to adjacent windows

### ISSUE THREAD

**Issue by ng0177** [Leleat/Tiling-Assistant#180]
On smaller screens, snapped windows can become very small. Some users may appreciate just to have **tiling** as opposed to **snapping**. Thanks.

**Comment by Leleat** [comment]
> On smaller screens, snapped windows can become very small. Some users may appreciate just to have tiling as opposed to snapping

Sorry, not sure what you mean.

- Do you mean to disable the 'suggestion' of other windows to tile after a window is tiled?
- Do you mean to disable automatically raising all windows in a tiled group?
- Do you mean to disable that windows will try to adapt their size based on the existing tiled windows?

**Comment by ng0177** [comment]
> Do you mean to disable that windows will try to adapt their size based on the existing tiled windows?
Yes, precisely.

**Comment by Leleat** [comment]
So the implication is that you don't want tiled windows of a tile group to resize or be raised together?

**Comment by ng0177** [comment]
> So the implication is that you don't want tiled windows of a tile group to resize or be raised together?

Yes, precisely.

**Comment by Leleat** [comment]
I've added an [advanced/hidden setting](https://github.com/Leleat/Tiling-Assistant/blob/main/GUIDE.md#hidden-settings) to completely disable tile groups. That means some of the features no longer work. Quoting the commit:

> [...] tiled windows will no longer adapt their size to other tiled windows nor be raised or resized together. The Dynamic Keybinding Behaviour 'Window Focus' and the Tiling Popup will also no longer work.

**Comment by ng0177** [comment]
Thanks. Under `Hidden Settings`, I am able to activate `Experimental / Advanced Settings (to show more in main preference window)` but which is the precise name for **completely disable tile groups**?

**Comment by Leleat** [comment]
> Thanks. Under Hidden Settings, I am able to activate Experimental / Advanced Settings (to show more in main preference window) but which is the precise name for completely disable tile groups? And the main preference window is the right location to find it

It's actually called `Disable Tile Groups` and in the hidden settings page itself.

![scr](https://user-images.githubusercontent.com/53054301/175768447-51cc4759-9a36-45ea-a8d4-516f3e7ba0b1.png)

Althoguh I guess it is confusing that I have a toggle to enable more settings for the 'main settings pages' and some settings on the hidden settings page itself. Guess I need to rework that at some point...

**Comment by ng0177** [comment]
I find it only now because I previously did not have the git version installed from aur. However, when testing with two terminal windows on left and right screen halfs respectively, they are still grouped i.e. snapped together. The aur git version used is r316.642278e8-1.

**Comment by Leleat** [comment]
> I find it only now because I previously did not have the git version installed from aur. However, when testing with two terminal windows on left and right screen halfs respectively, they are still grouped i.e. snapped together. The aur git version used is r316.642278e8-1.

I don't maintain the AUR packages. It looks like the git version on the AUR is outdated. The commit `64227e8` is from Oct '21. The other AUR package seems to be up-to-date with EGO's version. For you to see the setting you need to update to the current `main` branch. (Or switch to the other AUR package/EGO version and wait until I release version 34 in 2 weeks or so.)

**Comment by ng0177** [comment]
I shall wait for 2 weeks then. It is still interesting to see this option appearing in commit `64227e8` but probably not with that functionality.

**Comment by Leleat** [comment]
> I shall wait for 2 weeks then. It is still interesting to see this option appearing in commit 64227e8 but probably not with that functionality.

Huh, you can see the setting as it is depicted in my screenshot above? 

I have no idea how the AUR works. But if that's the case I guess maybe `64227e8` is only the starting commit the AUR package points to and it actually pulls directly from `main`... 

Then the issue might be something else. Did you reload GNOME Shell after updating the package?

**Comment by ng0177** [comment]
> Huh, you can see the setting as it is depicted in my screenshot above?
Yes, very odd. I sent an e-mail to the maintainer of this [aur package](https://aur.archlinux.org/packages/gnome-shell-extension-tiling-assistant-git).

> This is the behaviour you wanted when you say that windows shouldn't snap, right?
As a matter of fact that feature is working but only a subset of what is desired :-)

I expect any change of window size by the extension to be disabled other than tiling a window to a corner or a half of the screen thus avoiding any tiled window to become smaller than half of the screen.

**Comment by Leleat** [comment]
> I expect any change of window size by the extension to be disabled

> A good example is two terminals tiled to the left and the right half of the screen. When dragging one of them to become larger, then the other one should not change.

That's already happening in `main` if you use the setting `Disable Tile Groups`. All the followings things will be disabled if you enable that setting:

- tile groups will no be raised to the foreground together
- tile groups will not resize in sync
- the Tiling Popup will no longer appear after a window is tiled and there is free screen space
- Windows will no longer adapt their size to the visible tile group

Here is an example 

![output](https://user-images.githubusercontent.com/53054301/175783403-55a24c35-d887-4ddc-bd2a-b702a2249b3d.gif)

If that isn't working, did you reload GNOME Shell after updating the extension (ie log out and back in again)?

**Comment by ng0177** [comment]
`gnome-shell-extension-tiling-assistant-git  r512.7bbc969-1    0.42 MiB` so I noticed when reinstalling.

**Comment by ng0177** [comment]
> If that isn't working, did you reload GNOME Shell after updating the extension (ie log out and back in again)?
That is precisely what I need. However, for some reason not working even after a reboot.
![tiling](https://user-images.githubusercontent.com/34538954/175784385-b7f6e0fd-dbff-4d0d-b213-2103ed5f3e40.png)

**Comment by Leleat** [comment]
1. Please provide some system Info
    - Distro (version)
    - GNOME Shell version
    - Xorg vs Wayland

2. Do you get any errors in `journalctl -fo cat /usr/bin/gnome-shell`?

3. What other extensions do you have enabled?

Can you also please post a screencast of what the exact issue is?

**Comment by Leleat** [comment]
Also please post the extension settings with `gsettings --schemadir ~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/schemas list-recursively org.gnome.shell.extensions.tiling-assistant` here

**Comment by ng0177** [comment]
In a different location, we have
```
cube2: ~ $ gsettings --schemadir /usr/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/schemas list-recursively org.gnome.shell.extensions.tiling-assistant
org.gnome.shell.extensions.tiling-assistant activate-layout0 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout1 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout10 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout11 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout12 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout13 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout14 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout15 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout16 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout17 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout18 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout19 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout2 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout3 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout4 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout5 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout6 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout7 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout8 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout9 @as []
org.gnome.shell.extensions.tiling-assistant adapt-edge-tiling-to-favorite-layout false
org.gnome.shell.extensions.tiling-assistant auto-tile @as []
org.gnome.shell.extensions.tiling-assistant center-window @as []
org.gnome.shell.extensions.tiling-assistant changelog-version 33
org.gnome.shell.extensions.tiling-assistant debugging-free-rects @as []
org.gnome.shell.extensions.tiling-assistant debugging-show-tiled-rects @as []
org.gnome.shell.extensions.tiling-assistant default-move-mode 0
org.gnome.shell.extensions.tiling-assistant disable-tile-groups true
org.gnome.shell.extensions.tiling-assistant dynamic-keybinding-behaviour 0
org.gnome.shell.extensions.tiling-assistant enable-advanced-experimental-features true
org.gnome.shell.extensions.tiling-assistant enable-hold-maximize-inverse-landscape false
org.gnome.shell.extensions.tiling-assistant enable-hold-maximize-inverse-portrait false
org.gnome.shell.extensions.tiling-assistant enable-raise-tile-group false
org.gnome.shell.extensions.tiling-assistant enable-tile-animations true
org.gnome.shell.extensions.tiling-assistant enable-tiling-popup false
org.gnome.shell.extensions.tiling-assistant enable-untile-animations true
org.gnome.shell.extensions.tiling-assistant favorite-layout -1
org.gnome.shell.extensions.tiling-assistant favorite-layouts @as []
org.gnome.shell.extensions.tiling-assistant horizontal-preview-area 15
org.gnome.shell.extensions.tiling-assistant import-layout-examples false
org.gnome.shell.extensions.tiling-assistant maximize-with-gap false
org.gnome.shell.extensions.tiling-assistant move-adaptive-tiling-mod 0
org.gnome.shell.extensions.tiling-assistant move-favorite-layout-mod 1
org.gnome.shell.extensions.tiling-assistant restore-window ['<Super>Down']
org.gnome.shell.extensions.tiling-assistant restore-window-size-on 0
org.gnome.shell.extensions.tiling-assistant screen-bottom-gap 0
org.gnome.shell.extensions.tiling-assistant screen-left-gap 0
org.gnome.shell.extensions.tiling-assistant screen-right-gap 0
org.gnome.shell.extensions.tiling-assistant screen-top-gap 0
org.gnome.shell.extensions.tiling-assistant search-popup-layout @as []
org.gnome.shell.extensions.tiling-assistant show-changelog-on-update false
org.gnome.shell.extensions.tiling-assistant show-layout-panel-indicator false
org.gnome.shell.extensions.tiling-assistant tile-bottom-half ['<Super>KP_2']
org.gnome.shell.extensions.tiling-assistant tile-bottomleft-quarter ['<Super>KP_1']
org.gnome.shell.extensions.tiling-assistant tile-bottomright-quarter ['<Super>KP_3']
org.gnome.shell.extensions.tiling-assistant tile-edit-mode @as []
org.gnome.shell.extensions.tiling-assistant tile-left-half ['<Super>Left', '<Super>KP_4']
org.gnome.shell.extensions.tiling-assistant tile-maximize ['<Super>Up', '<Super>KP_5']
org.gnome.shell.extensions.tiling-assistant tile-maximize-horizontally @as []
org.gnome.shell.extensions.tiling-assistant tile-maximize-vertically @as []
org.gnome.shell.extensions.tiling-assistant tile-right-half ['<Super>Right', '<Super>KP_6']
org.gnome.shell.extensions.tiling-assistant tile-top-half ['<Super>KP_8']
org.gnome.shell.extensions.tiling-assistant tile-topleft-quarter ['<Super>KP_7']
org.gnome.shell.extensions.tiling-assistant tile-topright-quarter ['<Super>KP_9']
org.gnome.shell.extensions.tiling-assistant tilegroups-in-app-switcher false
org.gnome.shell.extensions.tiling-assistant tiling-popup-all-workspace false
org.gnome.shell.extensions.tiling-assistant toggle-always-on-top @as []
org.gnome.shell.extensions.tiling-assistant toggle-maximize-tophalf-timer 600
org.gnome.shell.extensions.tiling-assistant toggle-tiling-popup @as []
org.gnome.shell.extensions.tiling-assistant vertical-preview-area 15
org.gnome.shell.extensions.tiling-assistant window-gap 0
```

**Comment by ng0177** [comment]
Description:	EndeavourOS Linux
5.18.6-arch1-1
x11
Gnome Version 42.2
other extensions: Freon

`journalctl -fo cat /usr/bin/gnome-shell`
```
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55a007df0730] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55a007df46c0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55a006b4c330] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55a007df0730] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55a007df46c0] is on because it needs an allocation.
```

**Comment by ng0177** [comment]
https://user-images.githubusercontent.com/34538954/175802685-b1448320-cd5c-4fac-b9ed-625ec7499160.mp4

**Comment by Leleat** [comment]
I was able to figure out what it was; unfortunately, it's not something I can fix. It's GNOME's native snapping feature, which I cannot block/intercept in (a) GNOME Shell (extension). A workaround would be to use a window gap in Tiling Assistant's setting greater than 0.

**Comment by ng0177** [comment]
Sounds like a good workaround! If you do not mind posting a screenshot of where to find the window gap settings, I would appreciate it.

**Comment by Leleat** [comment]
![scr](https://user-images.githubusercontent.com/53054301/177000151-0bf7cef6-9fea-4057-beef-2b6e28480958.png)

**Comment by Leleat** [comment]
Actually, I am not sure anymore, if it's GNOME's native snapping. Since it behaviors differently now than when I tried. Did it work for you?

**Comment by ng0177** [comment]
Nope, it did not. I actually set the gap to 10 (unit?) and did not see windows separated that much.

**Comment by Leleat** [comment]
> Nope, it did not. I actually set the gap to 10 (unit?) and did not see windows separated that much.

10 px is the entire gap between 2 windows (e. g. 5 px on one side of the window and 5 px on the other side). That setting also doesn't affect already tiled windows.

It was this setting that interefered with the `Disable Tile Groups` setting.

> org.gnome.shell.extensions.tiling-assistant enable-raise-tile-group false

If you enable that setting (under the `General` tab the `Raise together` toggle), `Disable Tile Groups` should work as intended. This time I am sure 😅 since I was able to consistently reproduce your issue. Make sure to re-tile windows after enabling `Raise Together` again when you test it.

**Comment by ng0177** [comment]
I confirm, it does - problem solved by just a mouse click (on my side) :-)
