### ISSUE TITLE
Multi Monitor Super+8 snaps to wrong monitor

### ISSUE THREAD

**Issue by GrimHacker** [Leleat/Tiling-Assistant#182]
**Describe the bug**
3 monitor setup. Using Super+8 to try and snap gnome terminal to upper half of screen 3 results in the correct size window, but off the top of screen 1. Removing 2, and Super+8 correctly snaps gnome terminal to upper half of screen 3. (Google Chrome correctly snaps to upper half of screen 3 with all 3 monitors connected.)

![Screenshot from 2022-07-02 20-14-54](https://user-images.githubusercontent.com/3476150/177013787-47981f6b-1052-4835-ab3b-f0ca595df3d4.png)

**Steps To Reproduce**
Have 3 screens. Open gnome terminal on screen 3. Super+8.

**System Info:**
 - Distro (incl. version): Ubuntu 22.04 LTS
 - GNOME (Shell) version: 42.2
 - Extension version and from where (e. g. EGO, `main` branch...): 33 https://extensions.gnome.org/extension/3733/tiling-assistant/
 - XOrg/Wayland: Wayland

**Journalctl logs**
Error in size change accounting.

**Comment by Leleat** [comment]
> Extension version and from where (e. g. EGO, main branch...): 33 https://extensions.gnome.org/extension/3733/tiling-assistant/

Can you try to [install](https://github.com/Leleat/Tiling-Assistant#installation=) from the `main` branch and see if it fixes it? I fixed some multi monitor issues on Wayland there which sounded similiar to this.

**Comment by GrimHacker** [comment]
Installed from `main` and snapping the terminal works straight away.

Thanks very much the quick response (and already having fixed the problem!) :)

**Comment by Leleat** [comment]
Alright, thanks for the confirmation :)
