### ISSUE TITLE
Tiling assistant not working with touch screen on Fedora 36

### ISSUE THREAD

**Issue by newknowledg** [Leleat/Tiling-Assistant#183]
**Describe the bug**
Tiling assistant doesn't work with touch screen. 
**Steps To Reproduce**
Use Tiling-assistant with touch controls in Fedora 36
**System Info:**
 - Distro (incl. version): Fedora 36
 - GNOME (Shell) version: 42
 - Extension version and from where (e. g. EGO, `main` branch...): 33
 - XOrg/Wayland: Wayland

**Journalctl logs**

Error in size change accounting.

**Comment by Leleat** [comment]
There is already https://github.com/Leleat/Tiling-Assistant/issues/63 about this issue. Quoting myself from there

> If I am understanding https://gitlab.gnome.org/GNOME/mutter/-/issues/295 correctly, there is no proper way for me support touch on a Xorg session.
>
>As for Wayland, I don't know how touch works and I also don't have a touch device, so I cannot implement and test it. Someone else needs to do this.
