### ISSUE TITLE
Bad tiling on portrait mode screen

### ISSUE THREAD

**Issue by smarchevsky** [Leleat/Tiling-Assistant#186]
**Describe the bug**
Top window appears in wrong position.

**Steps To Reproduce**
- Tile first window bottom
- Choose second suggested window
- Second window appears in the middle, not on the top of the screen.

Or:
- Tile first window top
- It appears it the middle
- If you choose any window
- first remains in the middle

**System Info:**
 - Distro (incl. version): Ubuntu 22.04
 - GNOME (Shell) version: 42.2
 - Extension version and from where (e. g. EGO, `main` branch...): main, Ubuntu 22.04 version
 - Reproduces in XOrg and Wayland:

**Journalctl logs**

`Error in size change accounting.`
I dont know, what does it mean.

**Comment by Leleat** [comment]
I can't seem to reproduce it on Fedora 36.

> > Error in size change accounting.
> I dont know, what does it mean.

It's related to animations. Probably has nothing to do with this.

> Extension version and from where (e. g. EGO, main branch...): main, Ubuntu 22.04 version

Is it an up-to-date commit? If it isn't, please try the current `main` branch. If your `main` branch is already up-to-date

1. please provide the settings of Tiling Assistant with the following command `gsettings --schemadir ~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/schemas list-recursively org.gnome.shell.extensions.tiling-assistant`
2. please show a screenshot of you monitor setup from GNOME Preferences like [in this comment](https://github.com/Leleat/Tiling-Assistant/issues/137#issuecomment-1012586811)

**Comment by smarchevsky** [comment]
> I can't seem to reproduce it on Fedora 36.
But it is no longer reproducable on Ubuntu after extension update.

**Comment by Leleat** [comment]
> But it is no longer reproducable on Ubuntu after extension update.

Maybe you were on an older version of `main`? https://github.com/Leleat/Tiling-Assistant/commit/1e4176a9a7037ee5dd0612e4c9f9dbe45d4e67cf fixed a multi monitor issue which kinda sounded like your problem. Any way, feel free to reopen this, if you encounter the problem again.

**Comment by smarchevsky** [comment]
@Leleat thank you!
