### ISSUE TITLE
Grace time increased drastically with v34

### ISSUE THREAD

**Issue by dolwup** [Leleat/Tiling-Assistant#190]
**Describe the bug**
The tiling grace time increased drastically with version 34 or starts with a delay.

**Steps To Reproduce**
- Try tiling a window in a multi monitor setup
- observe

**System Info:**
 - Distro (incl. version): Arch Linux
 - GNOME (Shell) version: 42.3.1
 - Extension version and from where (e. g. EGO, `main` branch...): EGO v34 & main
 - XOrg/Wayland: Wayland

**Journalctl logs**
None

**Screencasts**

v34:

https://user-images.githubusercontent.com/38048361/179581542-471f2e86-7009-41fa-bfed-1326497ed09b.mp4

v33:

https://user-images.githubusercontent.com/38048361/179581667-6a6d24be-8d1a-4bc3-bcca-a3feaae87bbc.mp4

**Comment by Leleat** [comment]
So I made that 'performance improving' behaviour an opt-in setting called `Low Performance Movement Mode`. Can you test `main` and see, if the old behaviour is back for you?

**Comment by dolwup** [comment]
I just tested it and it restores the old behaviour

**Comment by Leleat** [comment]
Alright, thanks.
