### ISSUE TITLE
Window maximization behaviour change

### ISSUE THREAD

**Issue by kutzlect** [Leleat/Tiling-Assistant#194]
I started using this extension with v33 next to an extension which moved fullscreen and maximized windows to a new workspace. In that release it didn't really work with Super + Num Pad 5 so I used a built-in keybinding to achieve the wanted functionality.  
With v34 Super + Num Pad 5 seemed to work again to actually maximize the window. In the latest v35 release, this change is now reverted.  
Is there any reason behind this change? The v34 behavior was an ideal implementation in my opinion.  

Thanks for your great work on this useful extension!

**Comment by Leleat** [comment]
Probably related to the changes I introduced because of https://github.com/Leleat/Tiling-Assistant/issues/191. Do you have the setting `Maximized Windows` under the `Gaps` section in the `General` tab enabled?

**Comment by Leleat** [comment]
> Probably related to the changes I introduced because of https://github.com/Leleat/Tiling-Assistant/issues/191. Do you have the setting Maximized Windows under the Gaps section in the General tab enabled? If so, try disabling it.

Any update here?

**Comment by kutzlect** [comment]
> Probably related to the changes I introduced because of #191. Do you have the setting `Maximized Windows` under the `Gaps` section in the `General` tab enabled? If so, try disabling it.

Disabling `Maximized Windows` under the `Gaps` section resulted in the behaviour I wanted. Thanks for your help!
