### ISSUE TITLE
consistent gap size scale across different resolution displays

### ISSUE THREAD

**Issue by Rend0e** [Leleat/Tiling-Assistant#196]
**Describe the bug**
When setting gap size to any length etc 10, it looks fine on a 1080p monitor (with 100% scale) but appears half the size on the Laptop (4k screen with 200% scale). Is there a way to make the size consistent across differing screen resolution, etc should be 10 on 1080p and 20 on 4k screen?

**Steps To Reproduce**

**System Info:**
 - Distro (incl. version): Arch Liux
 - GNOME (Shell) version: 42.2
 - Extension version and from where (e. g. EGO, `main` branch...): main
 - XOrg/Wayland: Wayland

**Journalctl logs**

n/a

**Comment by Leleat** [comment]
Fixed it in `main` now. Feel free to test it and report any issues with it.

**Comment by Rend0e** [comment]
Thanks, works perfectly!
