### ISSUE TITLE
No dropshadow on tiled windows [feature request]

### ISSUE THREAD

**Issue by Chris611** [Leleat/Tiling-Assistant#198]
I absolutely love this! It's nearly perfect. I have only one feature request:

In standard Adwaita theme, maximized (or split screen) windows remove the drop-shadow around the Window and get squared corners. This behavior is lost when using Tiling-Assistant. Would it be possible to restore this, perhaps with an option?

Thanks for the effort!

**Comment by Leleat** [comment]
Tiling Assistant (and all other tiling extensions) just do 'fake tiling' by moving and resizing windows programmatically for the user. In the end however all windows are actually still floating windows. I **think** it's not possible to do this from an extension's point of view because as an extension we can only affect GNOME Shell.

**Comment by Chris611** [comment]
If I tile a GTK window without tiling-manager, the window gets CSS classes 'tiled-bottom tiled-right tiled-top'. Tiling-manager doesn't add these classes. If I add these classes by hand (or just 'tiled') the window does the behavior I described. Perhaps tiling-manager could add this class to the Window when tiling a window?

**Comment by Leleat** [comment]
> Edit: Yeah, ok. The meta-window thing doesn´t have something like get_style_context().add_class() exposed as would be the case in normal GTK. So I´t not as simple as I thought and probably not even possible in a gnome-shell extension indeed.. Big limitation of gnome-shell..

Closing this. As mentioned I don't think it's possible to do this from inside a GNOME Shell extension. I'll addt his to the list of known limitations...
