### ISSUE TITLE
Terminal window has inconsistant sizing

### ISSUE THREAD

**Issue by ejagombar** [Leleat/Tiling-Assistant#201]
**Describe the bug**
When I tile a terminal window, it will not quite take up the same amount of space at the bottom as other windows. 
Both the Firefox windows have an equal sized border on all sides however the terminal windows have a larger gap at the bottom.

The edge gap setting has been set to equal values for all sides in the extension settings. 

Other than this, the extension is amazing and works excellently.

**Steps To Reproduce**

Open a terminal and another program such as firefox and tile them next to each other.

**System Info:**
 - Distro (incl. version): Ubuntu 22.04.1
 - GNOME (Shell) version: 42.2
 - Extension version and from where (e. g. EGO, `main` branch...): From Repo, running newest version as of 18th August (V35 I think)
 - XOrg/Wayland: Wayland

**Journalctl logs**

**Comment by Leleat** [comment]
That is unfortunately not something I can fix. It's a limitation of what I can do as a GNOME Shell extension. My (and other) tiling extensions only move and resize windows programmatically but are limited to 'what a user *could* do'.

For example GNOME Terminal only resizes in full rows/columns and not in pixels. That means you (a user) can't make GNOME Terminal fill the entire screen perfectly manually. So my extension can't do that either. Only solution is to switch to another the terminal. I believe GNOME's new default terminal `Console` allows free resizing. I think there is also a patched GNOME Terminal with free resizing. IIRC PopOS ships it.
