### ISSUE TITLE
Gnome terminal is slightly too short when tiled

### ISSUE THREAD

**Issue by raymondheil** [Leleat/Tiling-Assistant#203]
With the extension enabled, the window for gnome terminal is slightly too short whenever the window is tiled. This happens when tiled to any of the corners, or any half (upper, lower, left, or right) of the screen, but when the application is maximized with Super+Up it appears normally. This issue doesn't seem to happen with any other apps, including other terminal emulators. 

**Steps To Reproduce**

Open Gnome Terminal and tile to one side of the screen, with keyboard shortcuts or by dragging.

The bottom of the window appears about one row too short, showing the desktop background.

**System Info:**
 - Distro (incl. version): Fedora 36
 - GNOME (Shell) version: 42.4
 - Extension version and from where (e. g. EGO, `main` branch...): Gnome Extensions website (presumably `main` branch)
 - XOrg/Wayland: Wayland

**Journalctl logs**
Whenever the window is tiled or untiled, a message appears that reads

```
Error in size change accounting.
```

However, this also happens when unaffected apps such as Firefox are tiled or untiled.

**Comment by Leleat** [comment]
That is unfortunately not something I can fix. It's a limitation of what I can do as a GNOME Shell extension. My (and other) tiling extensions only move and resize windows programmatically but are limited to 'what a user could do'.

For example GNOME Terminal only resizes in full rows/columns and not in pixels. That means you (a user) can't make GNOME Terminal fill the entire screen perfectly manually. So my extension can't do that either. Only solution is to switch to another the terminal. For example, GNOME's new default terminal (`Console`) allows free resizing. I think there is also a patched GNOME Terminal with free resizing. IIRC PopOS ships it.

**Comment by raymondheil** [comment]
Thank you for explaining! I'll look into some other options like you suggest.
