### ISSUE TITLE
Use maximize window decoration style for tiled windows without gaps

### ISSUE THREAD

**Issue by axtimwalde** [Leleat/Tiling-Assistant#207]
It would be great if tiled windows could use the rectangular headerbar/ window decoration that they would use when maximized or 'tiled' by Gnome's default tiling (well ... two-column) mode. This would be particularly nice without gaps (which I prefer because no pixels wasted :).

**Comment by Leleat** [comment]
Unfortunately that isn't possible since that isn't being done in GNOME Shell, so I can't change it with a shell extension.
