### ISSUE TITLE
[Feature Request] Add ability to add more snap columns.

### ISSUE THREAD

**Issue by tsoulard** [Leleat/Tiling-Assistant#211]
In windows you are able to snap windows to 3 columns, this is especially helpful for ultrawide monitors. Being able to do the same with this extension would be incredibly helpful for wider monitors. An example can be found [here](https://thewincentral.com/windows-11-has-snap-layouts-with-3-columns-for-large-displays-improved-docking-multiple-monitor-experience/)

**Comment by Leleat** [comment]
You can do something like that with `Layouts` and choosing a favorite layout. See https://github.com/Leleat/Tiling-Assistant/blob/main/GUIDE.md on how to use it. You can also change the `Movement Mode` from `Edge Tiling` (ie snapping only at the screen edges) to `Favorite Layout` to always snap to the favorite layout. See the advanced settings.
