### ISSUE TITLE
Panel Indicator Icon is Broken

### ISSUE THREAD

**Issue by CoderRuq** [Leleat/Tiling-Assistant#218]
**Describe the bug**
On Arch Linux with GNOME 43, there is no visible icon for the tiling panel indicator.

**Steps To Reproduce**
I installed the AUR package to get this (excellent) extension, and during configuration decided to turn on the panel indicator, only to find there was no icon showing on the panel. 

The indicator is there, and works perfectly, but the icon isn't there.

I am unsure if I am possibly missing a dependancy that adds the missing icon, but I checked and found that such GNOME and Adwaita Icon Themes are in fact installed.

**System Info:**
 - Arch Linux (Up to Date since Today).
 - GNOME Shell Version: 43
 - Extension Version and Source: 36, the non-git version on the AUR.
 - Wayland w/ Nvidia Drivers

**Comment by Leleat** [comment]
> The indicator is there, and works perfectly, but the icon isn't there.

Do you see like a placeholder or something?

FTR, this is how the icon is supposed to look

![image](https://user-images.githubusercontent.com/53054301/206710688-e1d37932-d44b-4a29-83ac-b7007873036a.png)

> I am unsure if I am possibly missing a dependancy that adds the missing icon, but I checked and found that such GNOME and Adwaita Icon Themes are in fact installed.

The icon should ship with the extension itself. Can you find icons at `~.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/media`.

Do you see anything that looks relevant with `journalctl -fo cat /usr/bin/gnome-shell` when enabling the extension?

**Comment by CoderRuq** [comment]
There is no placeholder; It's invisible until you hover your mouse over it.

![image](https://user-images.githubusercontent.com/85083982/206736924-ea145df0-f969-4120-81f7-8882135c1df0.png)

![image](https://user-images.githubusercontent.com/85083982/206736971-c0adc829-dcd6-4372-84b5-993f758497fa.png)

I have no such directory as `.local/share/gnome-shell/extensions`. However I do have `/usr/share/gnome-shell/extensions`. The tiling extension is in there but there isn't any media folder!

Could it be my installation method at fault? (AUR package missing stuff?) I can always try installing the `git` AUR package version instead, or heck if I have to going and manually grabbing the extension from GNOME extensions through a browser.

I didn't include any `journalctl` output because I never saw anything that looked relevant. But here it is anyway:

```
Connection to xwayland lost
clutter_actor_get_preferred_width: assertion 'CLUTTER_IS_ACTOR (self)' failed
clutter_actor_get_preferred_height: assertion 'CLUTTER_IS_ACTOR (self)' failed
Starting ddterm app: ["/usr/share/gnome-shell/extensions/ddterm@amezin.github.com/com.github.amezin.ddterm","--undecorated"]
Error connecting to the screencast service
Failed to query filesystem: method Gio.File.query_filesystem_info_async: At least 4 arguments required, but only 3 passed
ddterm app exited with status 0
Error in size change accounting.
Error in size change accounting.
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
```

**Comment by Leleat** [comment]
> The tiling extension is in there but there isn't any media folder!

Ah, looks like I forgot to include that directory in the AUR PKGBUILD file.

https://github.com/Leleat/Tiling-Assistant/blob/main/scripts/aur-build/PKGBUILD#L20

(Other installations method should work find since I use a different script there...)

**Comment by CoderRuq** [comment]
Oh okay! Sounds like I can just update later and the issue should be fixed?

I'll close the issue then if that's the case. Thank you btw for such a timely response! I really appreciate the extension, as it vastly improves the GNOME experience.

**Comment by CoderRuq** [comment]
Yes I can switch to the EGO distribution! I can also go to the AUR can let the maintainer know about the missing folder.

Thank you! I'm closing this issue as resolved.

**Comment by willydee** [comment]
Please reopen this issue. I just installed v39 from EGO, and the extension itself works fine, but there's no icon. Also, there's no image file (neither svg nor png) in the installation path `/usr/share/gnome-shell/extensions/tiling-assistant@leleat-on-github`.

ArchLinux x86_64, kernel 6.0.12-arch1-1, GNOME version 43.2

**Comment by willydee** [comment]
Nope. I definitely installed it via extensions.gnome.org just an hour ago, and it landed in `/usr/share/gnome-shell/extensions/`. The Extensions app reports it in the `Built-In` section, active with version 39. Yes, I have enabled the Panel Indicator icon in the Advanced settings. The icon placeholder is there in the panel, the context menu too, but no icon.

**Comment by willydee** [comment]
Well, this is weird: it also appears in the installed packages in the Pamac manager :thinking:

I'll purge it completely, and install again from EGO.
