### ISSUE TITLE
Incorrect window sizing with Wezterm when used with Rounded Window Corners extension

### ISSUE THREAD

**Issue by aral** [Leleat/Tiling-Assistant#232]
**Describe the bug**

This is a niche one: when used with the [Rounded Window Corners](https://github.com/yilozt/rounded-window-corners/issues/47#) extension with [Wezterm](https://wezfurlong.org/wezterm/), under Wayland (Fedora Silverblue 37) it seems the window dimensions are incorrectly reported and the sizing is off (when asked to go full-screen, it looks tiled to just one-half visually but it’s actually taking up the space it normally would full-screen as other apps under it do not respond to mouse events).

I realise this may be nigh on impossible to reproduce and is likely on the Rounded Window Corners plugin’s end but thought I’d document it anyway.

**Steps To Reproduce**

**System Info:**
 - Distro (incl. version): Fedora Silverblue 37
 - GNOME (Shell) version: 43
 - Extension version and from where (e. g. EGO, `main` branch...): 39 (GNOME Extensions)
 - XOrg/Wayland: Watland

**Journalctl logs**

The only output I see is `Error in size change accounting.` but that also occurs when moving other windows (which move/resize correctly).

**Comment by Leleat** [comment]
While I use neither Rounded Window Corners and Wezterm, I can reproduce this after installing both und setting `window_decorations = "NONE"` in Wezterm's config file. But I don't think there is much I can do on my end...

**Comment by aral** [comment]
@Leleat Thanks for looking into it. I’ve had some weirdness with a few other windows too and it does seem to stem from the rounded window corners extension. Going to try and narrow it down when I can.

Please feel free to close this.
