### ISSUE TITLE
Alway-on-top windows break adaptive tiling (and resizing)

### ISSUE THREAD

**Issue by dolwup** [Leleat/Tiling-Assistant#235]
**Describe the bug**

(main screen = the screen you want to tile windows on)
When an always-on-top window is on the main screen, it becomes harder to trigger adaptive tiling mode. You need to refocus the tiled group after tiling another window over and over. 
When an alway-on-top window is on the second screen, adaptive tiling does not work at all and tiled windows don't resize together anymore. These are kinda two bugs but I think they are strongly related but if it would be better to split them up let me know.

**Steps To Reproduce**

1. Set a window to always-on-top
2. (Move that window to another monitor)
3. Try to use adaptive tiling mode
4. (Try to resize tiled windows together)

**System Info:**
 - Distro (incl. version): Arch Linux
 - GNOME (Shell) version: 43.3
 - Extension version and from where (e. g. EGO, `main` branch...): EOG
 - XOrg/Wayland: Wayland

**Journalctl logs**
The `Error in size change accounting.` seems unrelated since this gets logged regardless of any window being set to alway-on-top. The `grabbedsOldRect` blocks are logged when I try to resize a tiled window with an always-on-top window on the other screen.

```
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
JS ERROR: TypeError: grabbedsOldRect is undefined
_onResizeFinished@/home/dolwup/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/resizeHandler.js:299:36
TilingResizeHandler/g2<@/home/dolwup/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/resizeHandler.js:53:22

JS ERROR: TypeError: grabbedsOldRect is undefined
_onResizeFinished@/home/dolwup/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/resizeHandler.js:299:36
TilingResizeHandler/g2<@/home/dolwup/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/resizeHandler.js:53:22

JS ERROR: TypeError: grabbedsOldRect is undefined
_onResizeFinished@/home/dolwup/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/resizeHandler.js:299:36
TilingResizeHandler/g2<@/home/dolwup/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/resizeHandler.js:53:22

```
**Screencasts**
https://user-images.githubusercontent.com/38048361/221380469-a0c43b57-afce-404b-a3da-1dda7b8fba11.mp4

**Comment by 3v1n0** [comment]
FYI, you can simulate multiple monitors by just running GNOME shell in nested mode with env variables such as `MUTTER_DEBUG_NUM_DUMMY_MONITORS=2 MUTTER_DEBUG_DUMMY_MODE_SPECS="1920x1080:3840x2160:4096x2160:7680x4320:3840x2400:3200x1800:2650x1440:1024x768:800x600:1440x900:1680x1050:1680x1012"`

**Comment by Leleat** [comment]
@dolwup I've created a fix at https://github.com/Leleat/Tiling-Assistant/pull/240. Do you want to test it out before I merge it?

**Comment by dolwup** [comment]
#240 works perfectly 👍
