### ISSUE TITLE
Behavior change with Firefox tiled on the top edge of the screen

### ISSUE THREAD

**Issue by julienfalque** [Leleat/Tiling-Assistant#242]
**Describe the bug**
When Firefox is tiled in a way that makes it touch the top edge of the screen (e.g. on the right side or in the top-right corner), hovering the title bar with the mouse used to allow interacting with the tabs (e.g. closing one with a middle click or showing a context menu with a right click). However, it recently started to allow resizing the window instead, which is not really expected as the window is kind of maximized. The previous behavior was convenient because I could move the mouse to the top of the screen and close a tab quickly, now I need to move a few pixels down before I can do that.

I think this started happening with the latest Firefox update (snap package) but this only happens when Tiling Assistant is enabled. When the extension is disabled and Firefox is tiled to the left or the right side with native tiling, it works as before. So I'm not sure whether this is an issue in the extension.

Also, I only saw a change with Firefox, others apps I use already had this issue, but it was not a big deal because Firefox is the only app that I interact with on the top edge of the screen.

**Steps To Reproduce**
1. Open Firefox and tile it to the right side of the screen
2. Move the mouse to the very top of the screen, above a tab of Firefox
3. You should be able to close the tab with a middle click but the cursor actually shows that the mouse will resize the window instead

**System Info:**
 - Ubuntu 22.10
 - GNOME Shell version: 43.1
 - Extension version: 39 (installed from EGO)
 - Wayland

**Comment by Leleat** [comment]
> However, it recently started to allow resizing the window instead, which is not really expected as the window is kind of maximized. The previous behavior was convenient because I could move the mouse to the top of the screen and close a tab quickly, now I need to move a few pixels down before I can do that.

> Also, I only saw a change with Firefox, others apps I use already had this issue, but it was not a big deal because Firefox is the only app that I interact with on the top edge of the screen.

I didn't change anything recently; the last release (i. e. v39) was 4 months ago in Nov '22. I also can't reproduce the issue in a VM of Ubuntu 22.10. So maybe I misunderstood you. Could you please provide screencast of the problem?

**Comment by julienfalque** [comment]
I also noticed the issue on Arch Linux after upgrading Firefox from version 110 to 111, so it looks like something changed in Firefox itself that does not work well with TA enabled, and that's not related to Ubuntu nor its snap package. I'll try to make a screencast shortly.

**Comment by julienfalque** [comment]
Actually I can now reproduce this even with TA disabled, so definitely an issue in Firefox.
