### ISSUE TITLE
super+pointer actions don't trigger Tiling Assistant (GNOME 44)

### ISSUE THREAD

**Issue by oae** [Leleat/Tiling-Assistant#252]
**Describe the bug**

When I use Right mouse button with Super key to resize windows,  Tiling Assistant won't work.

**Steps To Reproduce**
1. Enable `Resize with Secondary-Click` in Gnome Tweaks
![image](https://user-images.githubusercontent.com/1043714/228179415-6cecbfa2-b71d-4ef4-b0f5-ef1c6ff67b5e.png)

2. Snap two windows side by side
3. Try `Super`+`RMB` to resize one of the windows
4. See they won't snap together
[Screencast from 2023-03-28 11-45-20.webm](https://user-images.githubusercontent.com/1043714/228181633-cde0e5b3-a62c-463d-856d-dd6ff0350f3f.webm)

**System Info:**
 - Distro (incl. version): Arch Linux
 - GNOME Shell version: 44
 - Extension version and from where (e. g. EGO, `main` branch...): main#31cee43deaf73b29f0349a7a1fdff5d18bbcf164
 - XOrg/Wayland: XOrg

**Journalctl logs**

No relevant logs

**Comment by Leleat** [comment]
Hmm, this seems to be a change on GNOME 44. It's not limited to just resizing with RMB but affects all  `Super` + mouse operations. I'll investigate it.

**Comment by Leleat** [comment]
I've opened https://github.com/Leleat/Tiling-Assistant/pull/253 which should fix this. Feel free to try it out. Otherwise you can just wait for me to merge it and create a new release.

**Comment by oae** [comment]
Thanks, this works now. :heart:
