### ISSUE TITLE
Info button in gnome extensions is broken

### ISSUE THREAD

**Issue by Nikolas-Lehto** [Leleat/Tiling-Assistant#254]
**Describe the bug**
Info button in the settings window of Gnome Extensions leads to the old "Leleat/Tiling-Assistant/blob/main/GUIDE.md"

**Steps To Reproduce**
Just open the settings window of the extensions. In the top-left corner there is a "( i )" button. When you click it, it opens a drop-down. There is a option called "User Guide" when you click it, then it opens github 404 page.

**System Info:**
 - Distro (incl. version): Heavily modified Ubuntu based distro of my own (it has no name _yet_)
 - GNOME Shell version: 43.1
 - Extension version and from where (e. g. EGO, `main` branch...): main
 - XOrg/Wayland: Wayland

**Journalctl logs**

No relevant entries

**Comment by Leleat** [comment]
> Extension version and from where (e. g. EGO, main branch...): main

This was already fixed in https://github.com/Leleat/Tiling-Assistant/pull/248. I guess you should pull again :)
