### ISSUE TITLE
Tiling states of windows on non-visible workspaces are lost after screen lock

### ISSUE THREAD

**Issue by dolwup** [Leleat/Tiling-Assistant#258]
**Describe the bug**
Tiled windows on other workspaces than the visible one don't get saved to `~/.config/tiling-assistant/tiledSessionRestore.json` and are lost after unlocking the screen again. This is propably related to #74 but the fix only respects the windows on the current workspace.

**Steps To Reproduce**
1. Tile some windows
2. Switch to another workspace
3. Lock & unlock screen
4. Try to resize the tiles windows, they won't resize together -> tiling states lost

**System Info:**
 - Distro (incl. version): Arch Linux
 - GNOME Shell version: 44.0
 - Extension version and from where (e. g. EGO, `main` branch...): EGO
 - XOrg/Wayland: Wayland

**Comment by Leleat** [comment]
I've opened https://github.com/Leleat/Tiling-Assistant/pull/259 that should fix this. Feel free to test it out.

**Comment by dolwup** [comment]
I just wanted to let you know that I used this for the last two days and didn't notice any new issues. Works flawlessly 👍
