### ISSUE TITLE
Alt dragging windows does not activate 'Favorite Layout' move mode [Regression]

### ISSUE THREAD

**Issue by fhackenberger** [Leleat/Tiling-Assistant#260]
With Ubuntu 22.04, I used to Alt drag windows and they would trigger the '_Favorite layout_' tiling mode, as I have it set in '_Settings -> General -> Default Window Movement Mode_'. Since the upgrade to 23.04 (and a newer tiling assistant extension) this doesn't work anymore.

I installed the extension from gnome.org and set the '_Default Window Movement Mode_' to '_Favorite Layout_'. I also made sure, none of the '_Settings->Other->'xxx' Move Mode Activator_' are set to '_Alt_'. The I activated one of my layouts as a 'favorite' and drag a window while holding down the 'Alt' key. I don't see any tiling indicators until I reach an edge. That's when the default edge tiling (not respecting my layout) start happening. However when I drag the window using its title bar, the 'Favorite Layout' movement mode works as expected.

I also tried setting all '_Move Mode Activator_' keys to Disabled. Same issue.

**System Info:**
 - Distro (incl. version): Ubuntu 23.04
 - GNOME Shell version: 44.0
 - Extension version and from where (e. g. EGO, `main` branch...): 40 from extensions.gnome.org
 - XOrg/Wayland: XOrg

**Journalctl logs**
No new entries, when I '_Alt_' drag a window. Using the title bar I get:
```
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x5609d4681920] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5609d6107a60] is on because it needs an allocation.
Error in size change accounting.
```

**Comment by Leleat** [comment]
I can't reproduce. It works as expected in an Ubuntu VM. Maybe there is a misunderstanding of the settings happening:

> **I installed the extension from gnome.org and set the 'Default Window Movement Mode' to 'Favorite Layout'**. I also made sure, none of the 'Settings->Other->'xxx' Move Mode Activator' are set to 'Alt'. **The I activated one of my layouts as a 'favorite' and drag a window while holding down the 'Alt' key.**

The default movement mode is the one that is activated when **no modifier** key is pressed. So if you've set the default mode to `Favorite Layout` and drag a window around with `Alt` (which I assume is your window action key), you need to release `Alt` for the previews of your favorite layout to appear after you started the drag.

If you want the previews of the favorite layout to appear, while holding `Alt`, you need to set `Favorite Layout Move Mode Activator` to `Alt` (and make sure that no other activator uses `Alt`) and the `Default Window Movement Mode` should be set to something else like `Edge Tiling`.

**Comment by fhackenberger** [comment]
Maybe adding something like this to the [Window-Grab-Modes](https://github.com/Leleat/Tiling-Assistant/wiki/Window-Grab-Modes) wiki page would help other users:

_When you grab a window with your window action key (usually Alt) to move it, you need to release the key before using the Activator keys to activate a non-default window-grab mode (Advanced settings)_

**Comment by Leleat** [comment]
Do you reopen this for the wiki entry or did you encounter another issue?

**Comment by fhackenberger** [comment]
For the Wiki entry, as I was unable to open a pull request for that.

**Comment by Leleat** [comment]
Okay, I've added a note to the wiki at the beginning of that page.
