### ISSUE TITLE
Probably user error, but only one window snaps to tile grid...

### ISSUE THREAD

**Issue by Paulie420** [Leleat/Tiling-Assistant#261]
When I move one window to lower-right grid it snaps there perfectly, but once one window is in any of those 1/4 screen lower-right, lower-left, upper-right, upper-left areas no other windows will snap to a 1/4 grid. When you drag the 2nd window to a 1/4 quadrant, the blue overlay goes all the way to the right/left and if you let go the 2nd window is almost all the way off the screen. I did notice that if I click to other windows first, SOMETIMES I can get a 2nd window to snap... but its not 'normal'.

Install tiling assistant, attempt to snap multiple windows to 1/4 quadrants. Only first window snaps correctly... 2nd window snaps almost all the way off the screen.

**System Info:**
 - Distro : Ubtuntu 22.04
 - GNOME Shell version: 42.5
 - Extension version and from where (e. g. EGO, `main` branch...): 36, from gnome extension website
 - XOrg/Wayland: Wayland

**Journalctl logs**

Error in size change accounting.
Error in size change accounting.
Error in size change accounting.

Thanks, you rockstars!!

**Comment by Leleat** [comment]
No user error, just a plain bug 🙃.

Tiling Assistant on EGO (the extensions website) only officially supports the latest GNOME Shell version. Unfortunately EGO doesn't support the concept of branches, so I can't really upload a fix for an older Tiling Assistant version.

So I am just going to post a fix here and you need to manually apply it to your local extension:

The file you need to edit is  `~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/utility.js`. Replace lines 485 - 501 with the following

```
getUnitAt(index, unitSize, orientation) {
    unitSize = Math.floor(unitSize);

    const isVertical = orientation === Orientation.V;
    const lastIndex = Math.round(this[isVertical ? 'width' : 'height'] / unitSize) - 1;

    const getLastRect = () => {
        const margin = unitSize * index;
        return new Rect(
            isVertical ? this.x +  margin : this.x,
            isVertical ? this.y : this.y + margin,
            isVertical ? this.width - margin : this.width,
            isVertical ? this.height : this.height - margin,
        );
    };
    const getNonLastRect = (remainingRect, idx) => {
        const firstUnitRect = new Rect(
            remainingRect.x,
            remainingRect.y,
            isVertical ? unitSize : remainingRect.width,
            isVertical ? remainingRect.height : unitSize
        );

        if (idx <= 0) {
            return firstUnitRect;
        } else {
            const remaining = remainingRect.minus(firstUnitRect)[0];
            return getNonLastRect(remaining, idx - 1);
        }
    };

    if (index === lastIndex) {
        return getLastRect();
    } else {
        return getNonLastRect(this, index);
    }
}
```

For reference, the lines you should replace look like this https://github.com/Leleat/Tiling-Assistant/blob/v36/tiling-assistant%40leleat-on-github/src/extension/utility.js#L485-L501.

Then restart GNOME Shell by logging out and back in again. That should fix the issue. Let me know, if it doesn't or if you notice any other problems!
