### ISSUE TITLE
Clarify the behavior of window movement modes in the preference window

### ISSUE THREAD

**Issue by mapleroyal** [Leleat/Tiling-Assistant#266]
**Describe the bug**
Ctrl+drag doesn't seem to have any effect whatsoever except that using ctrl with dragging (whether starting to hold it before dragging, or starting the dragging and then holding ctrl) disables any layouts-related tiling. Seems to have the same effect as dragging a window with super+drag.

**Steps To Reproduce**
1. Select `adaptive tiling` in `default window movement mode`
2. Have at least one window tiled per https://github.com/Leleat/Tiling-Assistant/issues/158#issuecomment-1105382783
3. Have some windows "in the way" that you want "pushed aside" by the adaptively-tiled window
4. (Example scenario has a window tiled to left half, and three sloppily placed floating windows on the right half)
5. Ctrl+drag one of the sloppy windows anywhere on the right half
6. Literally no layout-related tiling effect, let alone pushing windows out of the way, because holding ctrl disables layout features

**System Info:**
 - Distro (incl. version): Arch, up to date
 - GNOME Shell version: 44.1
 - Extension version and from where (e. g. EGO, `main` branch...): 41, from gnome extensions site
 - XOrg/Wayland: Wayland

**Journalctl logs**

This log may be misleading. I don't know how to clear it, so I can't show that none of these "errors" appear to result from trying to ctrl+drag. I can ctrl+drag many times and no new errors come up. The errors below simply happen either randomly, or affect a successful alt+drag.
```
journalctl -fo cat /usr/bin/gnome-shell
#2   563a744d62b8 i   resource:///org/gnome/shell/ui/calendar.js:796 (377770428240 @ 22)
== Stack trace for context 0x563a73edf570 ==
#0   563a744d63e8 i   resource:///org/gnome/shell/ui/messageTray.js:494 (3777704200b0 @ 84)
#1   563a744d6340 i   resource:///org/gnome/shell/ui/messageTray.js:489 (377770420060 @ 56)
#2   563a744d62b8 i   resource:///org/gnome/shell/ui/calendar.js:796 (377770428240 @ 22)
Object .Gjs_ui_messageTray_Notification (0x563a758ffab0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
INFO AppSettingsModel.js::init/this._settingsC(54) Prefrences/Settings value changed
Error in size change accounting.
INFO AppSettingsModel.js::init/this._settingsC(54) Prefrences/Settings value changed
Error in size change accounting.
INFO AppSettingsModel.js::init/this._settingsC(54) Prefrences/Settings value changed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
```

**Comment by Leleat** [comment]
It works fine here so I don't think this is a bug. Instead, I think there are some misunderstandings here.

> 1. Select adaptive tiling in default window movement mode

> 5. Ctrl+drag one of the sloppy windows anywhere on the right half

The default mode is the one activated when **no** modifier is pressed. So if you've set the default mode to `adaptive tiling`, do not press `ctrl`. Pressing `Ctrl` instead will activate the `Edge Tiling`.

> Have some windows "in the way" that you want "pushed aside" by the adaptively-tiled window

Note that only tiled windows may be 'pushed aside' and not floatiing windows. It's called 'adaptive tiling' because the visible layout will adapt to the dragged window. Check out this [wiki video](https://github.com/Leleat/Tiling-Assistant/wiki/Window-Grab-Modes#adaptive-tiling) for a demonstration.

That said, you are the second person in recent time to have been confused by this. So there is an explanation in the preference window missing and I need to clarify it there.

**Comment by neoq** [comment]
I also thought adaptive tiling was broken for me, but I found out that adaptive tiling only works when the <kbd>Super</kbd> key, that I use to drag windows, is released after grabbing. I always tried tiling while holding the <kbd>Super</kbd> key. Edge tiling works this way. I am not sure what the intended behavior is, I just wanted to add, that this may be another reason for confusion with regards to adaptive tiling.
