### ISSUE TITLE
Window in secondary display "jumps" and pixellates when switching workspaces on Primary-only workspaces.

### ISSUE THREAD

**Issue by erenfro** [Leleat/Tiling-Assistant#268]
**Describe the bug**

Windows in the secondary display in a multi-monitor setup, jumps and pixelates when switching workspaces. (video included in attachments).

**Steps To Reproduce**

GNOME Settings -> Multitasking -> Multi-Monitor -> Workspaces on primary display only.
With this enabled, use your keybindings to switch workspaces. Mine are Super+Ctrl+Left/Right to switch previous/next workspaces.

**System Info:**
 - Distro (incl. version): Fedora 38
 - GNOME Shell version: 44.1
 - Extension version and from where (e. g. EGO, `main` branch...): extensions.gnome.org 41
 - XOrg/Wayland: XOrg

**Journalctl logs**
(tl;dr -- No logs relevant to extension noticed)

[INFO   ][Another window session manager] Session 0xbc00007.json saved to /home/psi-jack/.config/another-window-session-manager/currentSession/Tilix/0xbc00007.json!
[INFO   ][Another window session manager] Session summary.json saved to /home/psi-jack/.config/another-window-session-manager/currentSession/summary.json!
[INFO   ][Another window session manager] Session summary.json saved to /home/psi-jack/.config/another-window-session-manager/currentSession/summary.json!
[INFO   ][Another window session manager] Session 0xbc00007.json saved to /home/psi-jack/.config/another-window-session-manager/currentSession/Tilix/0xbc00007.json!
[INFO   ][Another window session manager] Session summary.json saved to /home/psi-jack/.config/another-window-session-manager/currentSession/summary.json!
[INFO   ][Another window session manager] Session 0xbc00007.json saved to /home/psi-jack/.config/another-window-session-manager/currentSession/Tilix/0xbc00007.json!
[INFO   ][Another window session manager] Session summary.json saved to /home/psi-jack/.config/another-window-session-manager/currentSession/summary.json!
[INFO   ][Another window session manager] Session 0xbc00007.json saved to /home/psi-jack/.config/another-window-session-manager/currentSession/Tilix/0xbc00007.json!
[INFO   ][Another window session manager] Session summary.json saved to /home/psi-jack/.config/another-window-session-manager/currentSession/summary.json!
[INFO   ][Another window session manager] Session 0xbc00007.json saved to /home/psi-jack/.config/another-window-session-manager/currentSession/Tilix/0xbc00007.json!
[INFO   ][Another window session manager] Session 0xbc00007.json saved to /home/psi-jack/.config/another-window-session-manager/currentSession/Tilix/0xbc00007.json!

**Comment by erenfro** [comment]
[Video of Bug](https://files.linux-help.org/s/How8MPPENMn9Swm/download/Screencast%20from%202023-04-26%2011-13-17.webm)

**Comment by erenfro** [comment]
Note: Pixellation issue was not recorded in video, however existed visually watching it.

**Comment by erenfro** [comment]
This bug seems to be enabled by the Tiling Assistant settings under General -> Active Window Hint, if it's set to Minimal or Always, it causes the above video issue to occur, when not even relevant.

**Comment by Leleat** [comment]
That's actually a 'feature'. It may be hard to tell the focused window at a glance when switching workspaces while using tiled windows. That's why there is the scaling animation with the blue border effect _on the focused window_ when switching workspaces. 

As you already found out, you can disable it with the setting `Active Window Hint` set to disabled.

I will disable this feature in the future by default since there were other people who reported blurry windows with the animation.
