### ISSUE TITLE
Can't move tiled window using GNOME's "move to next monitor" shortcuts

### ISSUE THREAD

**Issue by notpeelz** [Leleat/Tiling-Assistant#269]
**Describe the bug**
If I tile a window on my 2nd monitor, the "Move window one monitor to the left/right" GNOME shortcuts stop working.

https://github.com/Leleat/Tiling-Assistant/assets/920910/588cda06-9915-42c8-b1b4-f19706c23788

In case you're wondering why my shortcuts are so weird, it's because I use [interception tools](https://gitlab.com/interception/linux/tools) to translate my Caps Lock key into Ctrl+Super+Alt.

`Caps+Shift+Left/Right` moves windows between monitors (GNOME shortcuts).
`Caps+Left/Right` for tiling windows to the left/right halfs of the current monitor.

I would try to reproduce this in a VM, but it gets a bit tricky when multiple monitors are involved.

Here are the relevant dconf settings (I can provide a more complete dump of my GNOME settings if necessary):
```
[org/gnome/desktop/wm/keybindings]
move-to-monitor-left=['<Ctrl><Super><Alt><Shift>Left']
move-to-monitor-right=['<Ctrl><Super><Alt><Shift>Right']

[/org/gnome/shell/extensions/tiling-assistant]
activate-layout0=@as []
activate-layout1=@as []
activate-layout2=@as []
activate-layout3=@as []
active-window-hint=0
active-window-hint-color='rgb(69,64,191)'
auto-tile=@as []
center-window=@as []
debugging-free-rects=@as []
debugging-show-tiled-rects=@as []
default-move-mode=0
disable-tile-groups=false
dynamic-keybinding-behavior=0
dynamic-keybinding-behaviour=0
enable-advanced-experimental-features=true
enable-raise-tile-group=false
enable-tile-animations=true
enable-untile-animations=true
favorite-layouts=['-1', '-1']
import-layout-examples=false
last-version-installed=41
monitor-switch-grace-period=true
move-adaptive-tiling-mod=3
overridden-settings={'org.gnome.mutter.edge-tiling': <false>}
restore-window=['<Ctrl><Super><Alt>Down']
search-popup-layout=['<Ctrl><Super><Alt>g']
show-layout-panel-indicator=false
tile-bottom-half=@as []
tile-bottom-half-ignore-ta=@as []
tile-bottomleft-quarter=['<Ctrl><Super><Alt>KP_1']
tile-bottomleft-quarter-ignore-ta=@as []
tile-bottomright-quarter=['<Ctrl><Super><Alt>KP_3']
tile-bottomright-quarter-ignore-ta=@as []
tile-edit-mode=@as []
tile-left-half=['<Ctrl><Super><Alt>KP_4', '<Ctrl><Super><Alt>Left']
tile-left-half-ignore-ta=@as []
tile-maximize=['<Ctrl><Super><Alt>Up', '<Ctrl><Super><Alt>KP_5']
tile-maximize-horizontally=@as []
tile-maximize-vertically=@as []
tile-right-half=['<Ctrl><Super><Alt>KP_6', '<Ctrl><Super><Alt>Right']
tile-right-half-ignore-ta=@as []
tile-top-half=['<Ctrl><Super><Alt>KP_8']
tile-top-half-ignore-ta=@as []
tile-topleft-quarter=['<Ctrl><Super><Alt>KP_7']
tile-topleft-quarter-ignore-ta=@as []
tile-topright-quarter=['<Ctrl><Super><Alt>KP_9']
tile-topright-quarter-ignore-ta=@as []
toggle-always-on-top=@as []
toggle-tiling-popup=@as []
```

**System Info:**
 - Distro: Arch
 - GNOME Shell version: 44.1
 - Extension version and from where: 41 (EGO)
 - XOrg/Wayland: Wayland

**Comment by Leleat** [comment]
Sorry for the late response.

This is a weird bug. Off the top of my head, I can't imagine why this issue would happen because of Tiling Assistant. It might be a GNOME bug. It appears that the shortcuts to move windows to a different monitor don't work, if the floating window is too big for the new monitor. 

To confirm my suspicion can you manually move/resize a floating window to the size/position of a tile (that's essentially all Tiling Assistatnt does) and try to press shortcut to move the window to the new monitor? If the issue still exists, it is an upstream bug and you should report it there (probably in mutter), if it wasn't reported yet. I couldn't find a preexisting issue for it atm.
