### ISSUE TITLE
Extension icon missing

### ISSUE THREAD

**Issue by vipseixas** [Leleat/Tiling-Assistant#272]
I installed the extension and its icon is missing, but the shortcuts work as expected. Already tried disabling all other extensions (from extensions app) and nothing changes. This is not the same as #218 as there is no hidden placeholder at the top bar.

I'm using:
- Ubuntu 22.04
- Gnome-Shell 42.5
- XOrg
- Installed the extension from EGO and version is 36 (checked in metadata.json)

Disabling/Enabling the extension shows nothing in journalctl.

**Comment by vipseixas** [comment]
> Maybe a silly question but did you enable it in the preference window (it's an advanced setting)?

Silly me for not understanding that the experimental features are hidden by default. I'm sorry...

**Comment by LucaFranceschini** [comment]
For the record, this was still an issue for me on Ubuntu 23.10. My extension folder is under /usr/share, I solved it by copying the media folder (with the whole path) under ~/.local/share and it now shows in the bar. Looks like it's being searched in the wrong place?

**Comment by Leleat** [comment]
> Looks like it's being searched in the wrong place?

@LucaFranceschini Can you please open a new issue with more information (e. g. which extension version, how you installed the extensions (e. g. are you using the vanilla extension or `Ubuntu Tiling Assistant`), etc.)? The extension should look for the image relative to the [extension location](https://github.com/Leleat/Tiling-Assistant/blob/main/tiling-assistant%40leleat-on-github/src/extension/layoutsManager.js#L464-L467).

**Comment by LucaFranceschini** [comment]
> 
> @LucaFranceschini Can you please open a new issue with more information (e. g. which extension version you've installed, how you installed the extension (e. g. are you using the vanilla extension from EGO or `Ubuntu Tiling Assistant`), etc.)? The extension should look for the image relative to the [extension location](https://github.com/Leleat/Tiling-Assistant/blob/main/tiling-assistant%40leleat-on-github/src/extension/layoutsManager.js#L464-L467).

I used to have it installed through the browser connector. In an attempt to reproduce the issue with a clean install, I now installed it through the Extension Manager (Ubuntu) and it seems to work fine.

Well, since Ubuntu now ships with snap-installed browsers, and snap applications can't install GNOME extensions because they don't support native host messaging application, I guess this is the currently supported way to install extensions on Ubuntu, so... all is well. Thank you.
