### ISSUE TITLE
Overlapping windows problem

### ISSUE THREAD

**Issue by EdiDD** [Leleat/Tiling-Assistant#277]
**Describe the bug**
When i have two windows tilled - one for left and one for right. I can easily switch between them using alt+tab or mouse but when i open another window and tilled to e.g. left pane = new widow is overlapping previous left and now when i click or switch to the right window previous left instantly overlaps new left (like in always on top mode). How to prevent this behavior ?

**Steps To Reproduce**

**System Info:**
 - Distro (incl. version): trixie
 - GNOME Shell version: 43.6-1
 - Extension version and from where (e. g. EGO, `main` branch...): EGO, 41 
 - XOrg/Wayland: wayland

**Comment by Leleat** [comment]
See https://github.com/Leleat/Tiling-Assistant/wiki/Tile-Groups

**Comment by EdiDD** [comment]
Ok. Thanks. It works with raise together disabled.
