### ISSUE TITLE
Adaptive Tiling only works on Monitor you started dragging on

### ISSUE THREAD

**Issue by dolwup** [Leleat/Tiling-Assistant#278]
**Describe the bug**
When dragging a window to another monitor triggering adaptive tiling mode (through ctrl or just on by default) does not work. One has to drop the window on the target monitor and pick it up again to make adative tiling work on that monitor. 

**Steps To Reproduce**
1. Drag window to another monitor
2. Try initiating adaptive tiling mode without dropping the window first
3. Adaptive tiling mode does not work

**System Info:**
 - Distro (incl. version): ArchLinux
 - GNOME Shell version: 44.3
 - Extension version and from where (e. g. EGO, `main` branch...): EGO
 - XOrg/Wayland: Wayland

**Journalctl logs**
Doesn't print new entries.

**Comment by Leleat** [comment]
Feel free to try out the branch at https://github.com/Leleat/Tiling-Assistant/pull/279 and report any regressions, if you do. I'll merge it next week.

**Comment by dolwup** [comment]
I used it for the past 3 days and didn't notice any regression 👍

**Comment by Leleat** [comment]
Thanks for the feedback, merged.
