### ISSUE TITLE
Can I disable the Tiling Popup by default for new users?

### ISSUE THREAD

**Issue by donateur** [Leleat/Tiling-Assistant#282]
**Hello, thanks so much for Tiling-Assistant!**

I wish Gnome would merge this functionality in to their window manager, it's invaluable.  I read that Canonical are looking to include it in Ubuntu versions by default and have packaged it in their 23.04 release too.

I am installing Tiling-Assistant by default in a Workstation image for multiple users.  Is there a way that I can disable the Tiling Popup for all new users by default but not prevent them from enabling it later?  While I understand some people like it, I find the Tiling Popup interrupts my work flow and don't want to jar new users (who have come from Gnome desktops without Tiling-Assistant).

I looked through the prefs.js but I presume it's reading from the user's settings database.  Is there an easy way to achieve this please?

Thank you!

PS: I'm using Ansible to deploy the zip in to a user's ~/.local/share/gnome-shell/extensions directory, so I'm happy to have it also patch anything I need to do on install, rather than permanently modify the source.

**Comment by Leleat** [comment]
The extension uses [gsettings](https://wiki.gnome.org/HowDoI/GSettings) to store the settings. So in a shell script (I don't know Ansible) you would run 

```shell
gsettings --schemadir ~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/schemas set org.gnome.shell.extensions.tiling-assistant enable-tiling-popup false
```

to disable the setting.

**Comment by donateur** [comment]
Awesome thanks @Leleat !

**Comment by donateur** [comment]
Unfortunately this ultimately does not work unless the user is actually logged in at the time.  The gsettings utility reports "Cannot autolaunch D-Bus without X11 $DISPLAY" and the settings are not applied.

I need to be able to run this before a user logs in to ensure the extension is fully configured by default.

**Comment by Leleat** [comment]
In that case you can modify https://github.com/Leleat/Tiling-Assistant/blob/main/tiling-assistant%40leleat-on-github/schemas/org.gnome.shell.extensions.tiling-assistant.gschema.xml#L8 (and recompile the settings).

**Comment by donateur** [comment]
> In that case you can modify https://github.com/Leleat/Tiling-Assistant/blob/main/tiling-assistant%40leleat-on-github/schemas/org.gnome.shell.extensions.tiling-assistant.gschema.xml#L8 (and recompile the settings).

Thank you agian!
Could you please send me a pointer to how the settings are 'recomplied'?  I've done a quick search but haven't found anything relevant.

**Comment by Leleat** [comment]
See https://github.com/Leleat/Tiling-Assistant/blob/main/scripts/build.sh#L11C1-L11C12

**Comment by Leleat** [comment]
That said, I don't know if compiling the schemas has any 'user specificness'. That would be too deep into non-extension related GNOME stuff where I can't really help anymore...

**Comment by donateur** [comment]
I'm half tempted to install the extension system-wide and make it mandatory.  Then I can disable all user GNOME extensions for security reasons.

It wouldn't be as user-friendly but security...

**Comment by Leleat** [comment]
My bad, when I said 'user-specficness' I actually meant system specfic. From googling, it seems to be discouraged to ship compiled `gschema.compiled` directly. It seems to be recommended to have it be compiled on the system. But in the past extensions shipped the compiled file rather than just the .xml file)... so pre-compiling may work I guess.
