### ISSUE TITLE
Allow "Restore Window Size" shortcut to be used for minimizing, or tile window to bottom corner

### ISSUE THREAD

**Issue by ek-is-anika** [Leleat/Tiling-Assistant#283]
**Briefly describe how the feature should work (Minimize)**
After using the `Super` + `Down` keybinding to un-tile the window, and
"Tiling State (Windows)" is the selected Dynamic Keybinding Behavior,
minimize the window.

**Briefly describe how the feature should work (Tile to bottom corner)**
After using the `Super` + `Left`/`Right` keybinding to tile the window- to the left/right half of the workspace, and
"Tiling State" is the selected Dynamic Keybinding Behavior,
tile the window to the bottom left if the window is tiled to the left, or to the bottom right if the window is tiled to the right

**Explain why this feature should be added**
In case of a user (like me) that does not have a numpad,
we should be able to use `Super` + `Down` for minimize or tile the window to the bottom corners.

**Comment by Leleat** [comment]
I'm not sure I understand your problem. You are essentially asking describing the current behaviour of `Tile to bottom` so you want for `Restore Window Size` to behave like `Tile to bottom` when using the 'dynamic keybindings'? Is there a reason why you just can't use `Tile to bottom`? `Restore Window Size` is meant to be an 'escape all tiling'.

**Comment by ek-is-anika** [comment]
I just came home, so I wasn't able to respond... so apologies to that. I bound `Super + Down` to `Tile to Bottom`, and I can see that what you said here:
> You are essentially describing the current behaviour of Tile to bottom

is exactly what I described. Now the tiling behaviour is like Cinnamon, or KDE Plasma, where you can use the arrow keys to to half or quarter tiling, de-tiling, maximizing and minimizing.

**Comment by Leleat** [comment]
That's what you originally asked for, right? So this issue can be closed?

**Comment by ek-is-anika** [comment]
Yes, it was! I'll close it with this comment.
