### ISSUE TITLE
bug wont let me see all the settings (arch-based)

### ISSUE THREAD

**Issue by kimo-supremo** [Leleat/Tiling-Assistant#294]
**Describe the bug**
I cant see all the settings of the extension

**Steps To Reproduce**
I just kept all my packages up to date and found it like this since yesterday

**System Info:**
 - Distro (incl. version): EndeavourOS latest
 - GNOME Shell version: 44.5
 - Extension version and from where (e. g. EGO, `main` branch...): Extension Manager version 43
 - XOrg/Wayland: xorg

**Journalctl logs**
The settings of extension tiling-assistant@leleat-on-github had an error:
```
TypeError: headerbar.pack_start is not a function
```

Stack trace:
```
_addHeaderBarInfoButton@/home/kemo/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/prefs.js:254:15
fillPreferencesWindow@/home/kemo/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/prefs.js:68:28
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:27:29
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:110:14
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by Leleat** [comment]
[This branch](https://github.com/Leleat/Tiling-Assistant/tree/fix-prefs-headerbar-gnome-44) should fix it. Do you want to try it? If not, I can just upload it to EGO.

**Comment by kimo-supremo** [comment]
I'm sorry I don't know what I'm supposed to do

**Comment by Leleat** [comment]
> I'm sorry I don't know what I'm supposed to do

Alright, I've uploaded a new version (v45) to EGO now. That should fix it. Please report back, if it doesn't.
