### ISSUE TITLE
Arch GNOME 45 - import declaration error

### ISSUE THREAD

**Issue by EccTM** [Leleat/Tiling-Assistant#295]
**Describe the bug:**

Updated to GNOME 45 today, and can no longer enable the extension.

**Steps To Reproduce:**

1. Install the extension from extensions.gnome.org
2. Receive error message in GNOME Extensions: `import declarations may only appear at top level of a module`

**System Info:**

 - Distro (incl. version): Arch Linux
 - GNOME Shell version: 45
 - Extension version and from where (e. g. EGO, `main` branch...): 44, EGO
 - XOrg/Wayland: Wayland

**Journalctl logs:**

````
JS ERROR: Extension tiling-assistant@leleat-on-github: SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/shell/ui/main.js:3:0
````

**Comment by EccTM** [comment]
I fixed this issue for myself by downloading the gnome-shell 45, version 44 .zip from EGO and manually installing it.

I'm not sure if there was cruft from a previous version (that removing and re-installing didn't initially clear) or if the extra reboot as part of the manual installation sorted it, but I'm gonna close this issue for now, with the assumption that I was my own issue. 🥲

**Comment by rubin55** [comment]
The extension is disabled for me too; what am I as a user expected to do? Shouldn't an update be pushed to extensions.gnome.org which fixes and re-enables the extension for Gnome 45 users?

**Comment by Leleat** [comment]
> Shouldn't an update be pushed to extensions.gnome.org which fixes and re-enables the extension for Gnome 45 users?

EGO already has the version that supports GNOME Shell 45. So there isn't something I can do (from Tiling Assistant's point of view). I guess there is some issue in the upgrade process from GNOME/extensions. You can try to 

1. Remove the extension (either via the extensions app or by deleting `~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github`)
2. Reboot your system
3. Re-install the extension.

That should probably fix it.

**Comment by rubin55** [comment]
I went directly to extensions.gnome.org using Firefox + The Gnome Extensions extension in firefox. It showed me an "outdated" button and a green update botton right next to it. Clicking that upgraded the extension in-place, without a need to first uninstall it. Weird though that Gnome itself did not detect the updated extension and prompted to log out to update it (like it does for other extensions).

**Comment by nlflint** [comment]
I just upgraded Arch today and it upgraded to Gnome45 which broke a few extensions, including this one. 

Using Extension Manager, I just removed Tiling Assistant, and re-installed it via the browse tab. Worked instantly, no reboot required.
