### ISSUE TITLE
GNOME 45: The extension is incompatible with the current GNOME version

### ISSUE THREAD

**Issue by londonuk371** [Leleat/Tiling-Assistant#300]
The extension cannot start on Ubuntu 23.10.
Still I have inactivated the Ubuntu Tiling assistant before any install.

Error message:
Type name Gjs_extension_tilingWindowManager_TilingSignals is already registered

**System Info:**
Extension Version 44
Gnome: 45
Distro: Ubuntu 23.10
Wayland

**Journalctl logs**
JS ERROR: Extension tiling-assistant@leleat-on-github: Error: Type name Gjs_extension_tilingWindowManager_TilingSignals is already registered
registerGObjectType@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:542:50
_init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:515:33
registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:74:23
@file:///home/adamy/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js:1291:31
@resource:///org/gnome/shell/ui/init.js:21:20

**Comment by acathrow** [comment]
Thanks, just hit the same issue after upgrading , this fix worked perfectly

**Comment by clezag** [comment]
Same issue after Fedora 38 -> 39 upgrade, re-installing fixed it.

**Comment by gaborjonas** [comment]
Same issue here, logging out, restarting my PC doesn't solve it.

**Comment by Leleat** [comment]
> Same issue here, logging out or restarting my PC doesn't solve it.

Did you just restart your PC? The exact steps that should be pretty sure to work are

1. Uninstall the extension
2. Restart your PC
3. Re-install the extension (via EGO)

If that still doesn't work, try installing the extension [manually](https://github.com/Leleat/Tiling-Assistant#installation).
