### ISSUE TITLE
Keyboard shortcut for editing tiling doesn't work after update to Gnome 45

### ISSUE THREAD

**Issue by LostinSpacetime** [Leleat/Tiling-Assistant#303]
**Describe the bug**
Using a keyboard shortcut to edit the tiling, like sliding a window between two others, doesn't work. Before the Update to Gnome 45, I had Ctrl as a shortcut to edit the tiling. Afterwards, that shortcut was missing and I couldn't reactivate it. I tried other shortcuts and while they were registered in the GUI, they didn't do anything.
**Steps To Reproduce**
1. Set some shortcut for editing tiling.
2. Create or use an existing tiling setup.
3. While the tiling setup is in focus, grab another window and press the shortcut you set in 1.
4. Move the window and try to put it between two other windows. 
**System Info:**
 - Distro (incl. version): Fedora 49
 - GNOME Shell version: 45
 - Extension version and from where (e. g. EGO, `main` branch...): 44
 - XOrg/Wayland: XOrg

**Comment by Leleat** [comment]
Hmm, it's working for me on Fedora. What are your settings for Tiling Assistant? You can get them with 

```bash
gsettings --schemadir ~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/schemas list-recursively org.gnome.shell.extensions.tiling-assistant
```

**Comment by LostinSpacetime** [comment]
org.gnome.shell.extensions.tiling-assistant activate-layout0 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout1 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout10 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout11 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout12 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout13 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout14 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout15 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout16 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout17 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout18 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout19 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout2 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout3 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout4 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout5 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout6 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout7 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout8 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout9 @as []
org.gnome.shell.extensions.tiling-assistant active-window-hint 1
org.gnome.shell.extensions.tiling-assistant active-window-hint-border-size 5
org.gnome.shell.extensions.tiling-assistant active-window-hint-color 'rgb(53,132,228)'
org.gnome.shell.extensions.tiling-assistant active-window-hint-inner-border-size 0
org.gnome.shell.extensions.tiling-assistant adapt-edge-tiling-to-favorite-layout false
org.gnome.shell.extensions.tiling-assistant auto-tile @as []
org.gnome.shell.extensions.tiling-assistant center-window @as []
org.gnome.shell.extensions.tiling-assistant debugging-free-rects @as []
org.gnome.shell.extensions.tiling-assistant debugging-show-tiled-rects @as []
org.gnome.shell.extensions.tiling-assistant default-move-mode 0
org.gnome.shell.extensions.tiling-assistant disable-tile-groups false
org.gnome.shell.extensions.tiling-assistant dynamic-keybinding-behavior 0
org.gnome.shell.extensions.tiling-assistant enable-advanced-experimental-features false
org.gnome.shell.extensions.tiling-assistant enable-hold-maximize-inverse-landscape false
org.gnome.shell.extensions.tiling-assistant enable-hold-maximize-inverse-portrait false
org.gnome.shell.extensions.tiling-assistant enable-raise-tile-group true
org.gnome.shell.extensions.tiling-assistant enable-tile-animations true
org.gnome.shell.extensions.tiling-assistant enable-tiling-popup true
org.gnome.shell.extensions.tiling-assistant enable-untile-animations true
org.gnome.shell.extensions.tiling-assistant favorite-layout -1
org.gnome.shell.extensions.tiling-assistant favorite-layouts @as []
org.gnome.shell.extensions.tiling-assistant horizontal-preview-area 15
org.gnome.shell.extensions.tiling-assistant ignore-ta-mod 0
org.gnome.shell.extensions.tiling-assistant import-layout-examples false
org.gnome.shell.extensions.tiling-assistant last-version-installed 44
org.gnome.shell.extensions.tiling-assistant low-performance-move-mode false
org.gnome.shell.extensions.tiling-assistant maximize-with-gap false
org.gnome.shell.extensions.tiling-assistant monitor-switch-grace-period true
org.gnome.shell.extensions.tiling-assistant move-adaptive-tiling-mod 3
org.gnome.shell.extensions.tiling-assistant move-favorite-layout-mod 2
org.gnome.shell.extensions.tiling-assistant overridden-settings {'org.gnome.mutter.edge-tiling': <false>, 'org.gnome.desktop.wm.keybindings.maximize': <@mb nothing>, 'org.gnome.desktop.wm.keybindings.unmaximize': <@mb nothing>, 'org.gnome.mutter.keybindings.toggle-tiled-left': <@mb nothing>, 'org.gnome.mutter.keybindings.toggle-tiled-right': <@mb nothing>}
org.gnome.shell.extensions.tiling-assistant restore-window ['<Super>Down']
org.gnome.shell.extensions.tiling-assistant restore-window-size-on 0
org.gnome.shell.extensions.tiling-assistant screen-bottom-gap 0
org.gnome.shell.extensions.tiling-assistant screen-left-gap 0
org.gnome.shell.extensions.tiling-assistant screen-right-gap 0
org.gnome.shell.extensions.tiling-assistant screen-top-gap 0
org.gnome.shell.extensions.tiling-assistant search-popup-layout @as []
org.gnome.shell.extensions.tiling-assistant show-layout-panel-indicator false
org.gnome.shell.extensions.tiling-assistant single-screen-gap 0
org.gnome.shell.extensions.tiling-assistant tile-bottom-half ['<Super>KP_2']
org.gnome.shell.extensions.tiling-assistant tile-bottom-half-ignore-ta @as []
org.gnome.shell.extensions.tiling-assistant tile-bottomleft-quarter ['<Super>KP_1']
org.gnome.shell.extensions.tiling-assistant tile-bottomleft-quarter-ignore-ta @as []
org.gnome.shell.extensions.tiling-assistant tile-bottomright-quarter ['<Super>KP_3']
org.gnome.shell.extensions.tiling-assistant tile-bottomright-quarter-ignore-ta @as []
org.gnome.shell.extensions.tiling-assistant tile-edit-mode ['<Control><Alt>y']
org.gnome.shell.extensions.tiling-assistant tile-left-half ['<Super>Left', '<Super>KP_4']
org.gnome.shell.extensions.tiling-assistant tile-left-half-ignore-ta @as []
org.gnome.shell.extensions.tiling-assistant tile-maximize ['<Super>Up', '<Super>KP_5']
org.gnome.shell.extensions.tiling-assistant tile-maximize-horizontally @as []
org.gnome.shell.extensions.tiling-assistant tile-maximize-vertically @as []
org.gnome.shell.extensions.tiling-assistant tile-right-half ['<Super>Right', '<Super>KP_6']
org.gnome.shell.extensions.tiling-assistant tile-right-half-ignore-ta @as []
org.gnome.shell.extensions.tiling-assistant tile-top-half ['<Super>KP_8']
org.gnome.shell.extensions.tiling-assistant tile-top-half-ignore-ta @as []
org.gnome.shell.extensions.tiling-assistant tile-topleft-quarter ['<Super>KP_7']
org.gnome.shell.extensions.tiling-assistant tile-topleft-quarter-ignore-ta @as []
org.gnome.shell.extensions.tiling-assistant tile-topright-quarter ['<Super>KP_9']
org.gnome.shell.extensions.tiling-assistant tile-topright-quarter-ignore-ta @as []
org.gnome.shell.extensions.tiling-assistant tilegroups-in-app-switcher false
org.gnome.shell.extensions.tiling-assistant tiling-popup-all-workspace false
org.gnome.shell.extensions.tiling-assistant toggle-always-on-top @as []
org.gnome.shell.extensions.tiling-assistant toggle-maximize-tophalf-timer 600
org.gnome.shell.extensions.tiling-assistant toggle-tiling-popup @as []
org.gnome.shell.extensions.tiling-assistant vertical-preview-area 15
org.gnome.shell.extensions.tiling-assistant window-gap 0

**Comment by LostinSpacetime** [comment]
I set tile-edit-mode to <Control> in dconf-Editor and now I can adjust the Ratio of the tiling freely when I press Ctrl, but I still can't add a window.

**Comment by Leleat** [comment]
> I set tile-edit-mode to in dconf-Editor and now I can adjust the Ratio of the tiling freely when I press Ctrl, but I still can't add a window.

Maybe I misunderstood your original issue. `tile-edit-mode` is [this feature](https://github.com/Leleat/Tiling-Assistant/wiki/Tile-Editing-Mode). But I understood your original description of the problem that [this feature](https://github.com/Leleat/Tiling-Assistant/wiki/Window-Grab-Modes#adaptive-tiling) doesn't work. Could you clarify it please.

**Comment by LostinSpacetime** [comment]
I meant adaptive tiling. I thought tile-edit-mode was the key to activate it. Now I changed move-adaptive-tiling-mode to "1" and it works as expected. Is there a way to do it on the GUI?

**Comment by Leleat** [comment]
In the `General` preference tab under `Other` there is a dropdown box to change it. It's called `'Adaptive Tiling' Move Mode Activator`. Note that you need to have the [Advanced/Experimental Features]() enabled to see the settings.

**Comment by LostinSpacetime** [comment]
OK. So the “mode” is the key. It's still weird that the settings changed, since I didn't do it.
Thank you for your help. :)
