### ISSUE TITLE
Switching workspaces in GNOME sometimes moves window to wrong workspace for a brief moment

### ISSUE THREAD

**Issue by LogExE** [Leleat/Tiling-Assistant#306]
**Describe the bug**

When using the extension and trying to switch workspace while running particularly IntelliJ Idea IDE with other app tiled, an app from other workspace moves to next workspace and then disappears. That doesn't seem to happen when tiling assistant is turned off. (see video for example: https://github.com/Leleat/Tiling-Assistant/assets/27575516/2e1d74f7-66e2-46f8-af88-69c7d045d23f)

**Steps To Reproduce**

1. Open something alongside IntelliJ Idea in tiling mode
2. Open third app in other workspace
3. Move focus to IntelliJ Idea (press on it)
4. Try switching workspaces back and forth

**System Info:**
 - Distro (incl. version): Arch Linux, latest packages
 - GNOME Shell version: 45.1
 - Extension version and from where (e. g. EGO, `main` branch...): 44-1, from AUR, https://aur.archlinux.org/packages/gnome-shell-extension-tiling-assistant
 - XOrg/Wayland: Wayland (probably happens in Xorg too)

**Journalctl logs**
```
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Can't update stage views actor <unnamed>[<Gjs_dash-to-dock_micxgx_gmail_com_docking_DashSlideContainer>:0x55bfad78abb0] is on because it needs an allocation.
Can't update stage views actor <dashtodockBox>[<StBoxLayout>:0x55bfad78b9c0] is on because it needs an allocation.
Can't update stage views actor <dash>[<Gjs_dash-to-dock_micxgx_gmail_com_dash_DockDash>:0x55bfad76ffb0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StWidget>:0x55bfad785b60] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x55bfad7866f0] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashContainer>[<StBoxLayout>:0x55bfad770f40] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashScrollview>[<StScrollView>:0x55bfad771e40] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBoxLayout>:0x55bfad778830] is on because it needs an allocation.
Error in size change accounting.
Error in size change accounting.
```
(as I can tell, last two lines appeared during switching workspaces)

**Comment by Leleat** [comment]
Do you have the [Active Window Hint](https://github.com/Leleat/Tiling-Assistant/wiki/Active-Window-Hint) feature enabled?

**Comment by LogExE** [comment]
Yes, I do have "minimal" set

**Comment by LogExE** [comment]
Well, looks like I can just disable it as a workaround

**Comment by Leleat** [comment]
Thanks for the confirmation, then I have an idea what is gonig on.

**Comment by LogExE** [comment]
Speaking of IDEA, it seems that this IDE is not affected when moving tile border, it just stays still. But if you move the edge of other window, IDEA adjusts fine

**Comment by LogExE** [comment]
Nvm, it got fixed somehow

**Comment by LogExE** [comment]
I've noticed a glitch when moving tile border with one window being IDEA's, but it got fixed by itself somehow. When I was moving edge of IDEA window, firefox window was remaining still... I think issue gone away after me trying to move edge of firefox instead
