### ISSUE TITLE
Fullscreen tiling from application launch

### ISSUE THREAD

**Issue by dbergloev** [Leleat/Tiling-Assistant#311]
Hi. 

This is properly more of a feature if you look at it from certain perspectives, but it feels like a bug from a users perspective and as such I will report it as one. 

When configuring gaps between screen edges and the windows and apply this to also include fullscreen windows, it will only take affect on windows that has been manually tiled to fullscreen. Windows that is launching themself in fullscreen mode will do so in actual fullscreen (without the applyed gaps) and you will have to "re-tile" them every single time they launch.

**Comment by ehatari** [comment]
I have this same problem. I thinking about write issue but is here. I can confim this problem in my gnome.

**Comment by ser-drephs** [comment]
Same problem here. Hope this get's fixed ^^ For the time being I assigned Ctrl+Super+Up to "Toggle Maximization".

**Comment by Leleat** [comment]
Closing this as this feature request/bug report is already tracked in https://github.com/Leleat/Tiling-Assistant/issues/223
