### ISSUE TITLE
Cross-post: Ubuntu 23.10 Tiling Assistant stops working when Alt is set as the modifier button. 

### ISSUE THREAD

**Issue by maqp** [Leleat/Tiling-Assistant#313]
Hi, I'm not sure if the bug is in Canonical's domain or yours, so I thought it might be worth checking with you if it's a quick fix that can be applied by Canonical downstream before the LTS gets released. If it works for you it's probably only in Canonical's domain, so by all means ignore this. :)

This is a cross-post of the bug report I sent to Canonical in Oct 2023: 
https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-tiling-assistant/+bug/2039232 

**Describe the bug**

 Ubuntu 23.10 Tiling Assistant stops working when Alt is set as the modifier button. 

**Steps To Reproduce**

In Ubuntu 23.10, changing the window-move mouse button modifier from Super to Alt with e.g.

$ gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier '\<Alt\>'

and then trying to hold Alt while dragging the window from its center (or anything but the title bar), to edge/corner, does not perform tiling.

I also made a video that uses Gnome Tweaks to adjust the modifier and to demo the bug:

https://www.cs.helsinki.fi/u/oottela/ubuntu/tiling_bug.mp4

**System Info:**
 - **Package name:** gnome-shell-extension-tiling-assistant package (Ubuntu Tiling Assistant)
 - **Package version:** 44
 - **Distro (incl. version):** Ubuntu 23.10
 - **GNOME Shell version:** 44
 - **Extension version and from where (e. g. EGO, `main` branch...):** Bundled with the Ubuntu OS
 - **XOrg/Wayland:** Wayland

**Journalctl logs**

Since nothing is happening when dragging to corner, nothing is being written to journalctl. Here are whatever logs were printed before, hopefully they help.

JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in Get
_promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
@resource:///org/gnome/shell/ui/init.js:21:20
### Promise created here: ###
getProperty@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusProxy.js:89:33
refreshProperty@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:305:48
_refreshOwnProperties/<@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:191:32
_refreshOwnProperties@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:189:51
_onSignalAsync/refreshPropertiesPromises<@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:245:26
_onSignalAsync@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:244:50
async*_onSignal@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:203:14
_init/<@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusProxy.js:40:43
@resource:///org/gnome/shell/ui/init.js:21:20

JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in Get
_promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
@resource:///org/gnome/shell/ui/init.js:21:20
### Promise created here: ###
getProperty@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusProxy.js:89:33
refreshProperty@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:305:48
_refreshOwnProperties/<@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:191:32
_refreshOwnProperties@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:189:51
_onSignalAsync/refreshPropertiesPromises<@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:245:26
_onSignalAsync@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:244:50
async*_onSignal@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:203:14
_init/<@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusProxy.js:40:43
@resource:///org/gnome/shell/ui/init.js:21:20

JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in Get
_promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
@resource:///org/gnome/shell/ui/init.js:21:20
### Promise created here: ###
getProperty@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusProxy.js:89:33
refreshProperty@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:305:48
_refreshOwnProperties/<@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:191:32
_refreshOwnProperties@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:189:51
_onSignalAsync/refreshPropertiesPromises<@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:245:26
_onSignalAsync@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:244:50
async*_onSignal@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:203:14
_init/<@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusProxy.js:40:43
@resource:///org/gnome/shell/ui/init.js:21:20

JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: error occurred in Get
_promisify/proto[asyncFunc]/</<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:453:45
@resource:///org/gnome/shell/ui/init.js:21:20
### Promise created here: ###
getProperty@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusProxy.js:89:33
refreshProperty@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:305:48
_refreshOwnProperties/<@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:191:32
_refreshOwnProperties@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:189:51
_onSignalAsync/refreshPropertiesPromises<@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:245:26
_onSignalAsync@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:244:50
async*_onSignal@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:203:14
_init/<@file:///usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/dbusProxy.js:40:43
@resource:///org/gnome/shell/ui/init.js:21:20

meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed

**Comment by Leleat** [comment]
Sorry for the super late response. Tiling Assistant has different 'grab modes' which can be enabled by pressing certain modifiers. Here is an explanation about the different modes: https://github.com/Leleat/Tiling-Assistant/wiki/Window-Grab-Modes.

So this is intended behavior. Although I should probably check for the case when the user changes it.

**Comment by maqp** [comment]
Ubuntu seems to be using just edge tiling, and the fork in 23.10 doesn't seem to have the setting menu at all. I must say I didn't even realize this upstream version had settings, and the demo videos gave me a nice dose of FOMO, so I should probably see if I can override the plugin used and see if that fixes it the issue.

**Comment by maqp** [comment]
Okay, this is very interesting. I'm not sure if this is reproducible but I went with something like this:

1. Installed `leleat-tiling-assistant`, but it didn't enable.
2. Disabled Ubuntu's fork of the tiling assistant.
3. Tried to enable `leleat-tiling-assistant` but got a warning: `Type name Gjs_extension_tilingWindowManager_TilingSignals is already registered`.
4. Restarted the computer.
5. `leleat-tiling-assistant` was now active but changing window move modifier to  `Alt` from `Gnome Tweaks` didn't work.
6. Played around with a bunch of settings in `leleat-tiling-assistant`, didn't work. (this is what might break reproducibility)
7. Specifically tested other window grab modes, they all worked with `Alt`.
8. Tested Edge tiling mode again (that Ubuntu uses by default), it now also worked with `Alt`.
9. Tried reinstalling the `leleat-tiling-assistant`, and it now works out of the box. I can't seem to find the right files to delete to revert to previous state, but I'll see if I can find some time later to test this with a clean VM.

**Comment by Leleat** [comment]
FTR, (stock) Tiling Assistant checks if the `Window Action Key` is set to `Alt` and switches the `Super` and `Alt` activated grab mode modifiers. But that only happens during install/enable time of the extension. That means if you change the `Window Action Key` while Tiling Assistant is already enabled, there may be conflicts. I will extend the conflict check by monitoring changes to the gsetting.

**Comment by maqp** [comment]
Hooray! :tada: Thank you so much!
