### ISSUE TITLE
Make the split view windows resize when one of them is resized using keyboard

### ISSUE THREAD

**Issue by Fenimoure** [Leleat/Tiling-Assistant#316]
What I want:
1. Tile a window to the left
2. Tile another window to the right
3. In one of the windows press Alt+Space
4. In the menu choose "resize"
5. Resize a window

The other window should resize together with the one that is being resized using keyboard. Currently, this does not happen.

**Comment by xalt7x** [comment]
I believe it's the same issue as #187

**Comment by Leleat** [comment]
> I believe it's the same issue as #187

It is, thanks. Closing this in favor of the the earlier report.
