### ISSUE TITLE
Add 'shift' key as option under 'Favorite layout' Move Mode Activator

### ISSUE THREAD

**Issue by appel** [Leleat/Tiling-Assistant#320]
First off, thank you so much for developing this extension. It makes my desktop so much more useful on my ultrawide.

Please excuse me if this has been asked and answered before, I searched but could not find any issues mentioning this. Is there any way to add 'shift' as an option under `General > Other > Favorite layout Move Mode Activator`? I use FanzyZones on a Windows machine and the 'shift + mousedrag' combo is ingrained to the point of no return. :)

Thank you again!

**Comment by Leleat** [comment]
Sorry, for the late reply. Unfortunately, that is isn't possible as `Shift` is already taken by GNOME itself when dragging windows around.
