### ISSUE TITLE
Gaps Between Terminal Windows and Border of the Screen

### ISSUE THREAD

**Issue by Hosein-Rahnama** [Leleat/Tiling-Assistant#324]
I installed Tiling Assistant from gnome extensions website and I am on Ubuntu 20.04 LTS. All things work properly except for the terminal windows. There is always a gap between terminal windows and the border of the screen. See the following examples.

Here, you can see the gap between the two terminal windows and the right border of the screen.

![Screenshot from 2024-03-20 16-38-09](https://github.com/Leleat/Tiling-Assistant/assets/88373622/4f962c33-ee1a-49cd-a99b-c2cf9b60d67a)

Here, there is only a gap between the terminal window and the right border of the screen.

![Screenshot from 2024-03-20 16-40-12](https://github.com/Leleat/Tiling-Assistant/assets/88373622/13f491c8-72e2-4afe-8393-c90e5bb7d985)

**Comment by Leleat** [comment]
This isn't something I can fix. See https://github.com/Leleat/Tiling-Assistant/issues/111 for more info.

**Comment by taisph** [comment]
The stock tiling extension sizes the terminal window as expected without gaps, so shouldn't this extension be able to do so as well?

**Comment by Leleat** [comment]
> The stock tiling extension sizes the terminal window as expected without gaps, so shouldn't this extension be able to do so as well?

GNOME doesn't have a "stock tiling extension". If you mean GNOME's default behaviour, i. e. no extension enabled, that is implemented on a lower level than extensions have influence on. "GNOME Extensions" are __GNOME Shell__ extensions. So they are limited to what GNOME Shell can do... and GNOME Shell can't do much window management stuff.

Ofc, maybe there is some way to force windows to resize freely that I am not aware of... so if you do know of an extension that is able to achieve this, feel free to link me the extension and I'll take a look. But AFAIA, your only options are to live twith the gaps or use a terminal that doesn't resize discreetly like GNOME Terminal e. g. GNOME Console.

**Comment by taisph** [comment]
> > The stock tiling extension sizes the terminal window as expected without gaps, so shouldn't this extension be able to do so as well?
> 
> GNOME doesn't have a "stock tiling extension". If you mean GNOME's default behaviour, i. e. no extension enabled, that is implemented on a lower level than extensions have influence on. "GNOME Extensions" are **GNOME Shell** extensions. So they are limited to what GNOME Shell can do... and GNOME Shell can't do much window management stuff.

I was assuming it was a stock extension but I guess it is just Ubuntu's version of your(?) extension (which I may or may not have confused with WinTile which I use on a different box 😬)?

![image](https://github.com/Leleat/Tiling-Assistant/assets/814148/75fd65f0-38dc-4f9b-a003-e49d3f0c7936)

**Comment by Leleat** [comment]
> I was assuming it was a stock extension but I guess it is just Ubuntu's version of your(?) extension (which I may or may not have confused with WinTile which I use on a different box 😬).

Yeah, if it works in Ubuntu then they probably patched some stuff outside of the extension itself (maybe mutter or GNOME Terminal). If it was possible to achieve it only within the extension itself, they would probably have upstreamed it since I do recieve PRs from them in general.

**Comment by taisph** [comment]
FWIW, this is the patch they're using which makes the gaps disappear on my Ubuntu box. But it could very likely be something that only works on Ubuntu.

```patch
From: =?utf-8?b?Ik1hcmNvIFRyZXZpc2FuIChUcmV2acOxbyki?= <mail@3v1n0.net>
Date: Thu, 16 Mar 2023 07:14:24 +0100
Subject: tilingWindowManager: Override window constraints style

Use ubuntu-only function to override window edge constraints so that tiled
windows are correctly painted with no shadows and no rounded decorations.
---
 .../src/extension/tilingWindowManager.js             | 20 ++++++++++++++++++++
 1 file changed, 20 insertions(+)

diff --git a/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js b/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js
index ec592eb..e2c0b93 100644
--- a/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js
+++ b/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js
@@ -205,6 +205,20 @@ export class TilingWindowManager {
             );
         }
 
+        if (!maximize && window.override_constraints) {
+            const leftConstraint = newRect.x === workArea.x ?
+                Meta.WindowConstraint.MONITOR : Meta.WindowConstraint.WINDOW;
+            const rightConstraint = newRect.x2 === workArea.x2 ?
+                Meta.WindowConstraint.MONITOR : Meta.WindowConstraint.WINDOW;
+            const topConstraint = newRect.y === workArea.y ?
+                Meta.WindowConstraint.MONITOR : Meta.WindowConstraint.WINDOW;
+            const bottomConstraint = newRect.y2 === workArea.y2 ?
+                Meta.WindowConstraint.MONITOR : Meta.WindowConstraint.WINDOW;
+
+            window.override_constraints(topConstraint, leftConstraint,
+                rightConstraint, bottomConstraint);
+        }
+
         // See issue #137.
         // Under some circumstances it's possible that windows will tile to the wrong
         // monitor. I can't reproduce it but I suspect that it's because of passing
@@ -286,6 +300,12 @@ export class TilingWindowManager {
             );
         }
 
+        if (window.override_constraints) {
+            window.override_constraints(Meta.WindowConstraint.NONE,
+                Meta.WindowConstraint.NONE, Meta.WindowConstraint.NONE,
+                Meta.WindowConstraint.NONE);
+        }
+
         // userOp means that the window won't clamp to the workspace. For DND
         // we don't want to clamp to the workspace, so it's false by default.
         const userOp = !clampToWorkspace;
```

Patch command if others want to try:

```shell
patch -p2 -d ~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/ < ~/Downloads/tilingWindowManager-Override-window-constraints-style.patch
```

Pulled from https://launchpad.net/ubuntu/+source/gnome-shell-extension-tiling-assistant.

**Comment by Leleat** [comment]
As the commit message implies (and I did a quick search through the mutter code and couldn't find anything about `override_constraints`), it appears to require some Ubuntu (mutter) patch. So yeah... not something I can really do/fix from my _extension-only_ view. But thanks for looking into it!

**Comment by Hosein-Rahnama** [comment]
> FWIW, this is the patch they're using which makes the gaps disappear on my Ubuntu box. But it could very likely be something that only works on Ubuntu.
> 
> ```diff
> From: =?utf-8?b?Ik1hcmNvIFRyZXZpc2FuIChUcmV2acOxbyki?= <mail@3v1n0.net>
> Date: Thu, 16 Mar 2023 07:14:24 +0100
> Subject: tilingWindowManager: Override window constraints style
> 
> Use ubuntu-only function to override window edge constraints so that tiled
> windows are correctly painted with no shadows and no rounded decorations.
> ---
>  .../src/extension/tilingWindowManager.js             | 20 ++++++++++++++++++++
>  1 file changed, 20 insertions(+)
> 
> diff --git a/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js b/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js
> index ec592eb..e2c0b93 100644
> --- a/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js
> +++ b/tiling-assistant@leleat-on-github/src/extension/tilingWindowManager.js
> @@ -205,6 +205,20 @@ export class TilingWindowManager {
>              );
>          }
>  
> +        if (!maximize && window.override_constraints) {
> +            const leftConstraint = newRect.x === workArea.x ?
> +                Meta.WindowConstraint.MONITOR : Meta.WindowConstraint.WINDOW;
> +            const rightConstraint = newRect.x2 === workArea.x2 ?
> +                Meta.WindowConstraint.MONITOR : Meta.WindowConstraint.WINDOW;
> +            const topConstraint = newRect.y === workArea.y ?
> +                Meta.WindowConstraint.MONITOR : Meta.WindowConstraint.WINDOW;
> +            const bottomConstraint = newRect.y2 === workArea.y2 ?
> +                Meta.WindowConstraint.MONITOR : Meta.WindowConstraint.WINDOW;
> +
> +            window.override_constraints(topConstraint, leftConstraint,
> +                rightConstraint, bottomConstraint);
> +        }
> +
>          // See issue #137.
>          // Under some circumstances it's possible that windows will tile to the wrong
>          // monitor. I can't reproduce it but I suspect that it's because of passing
> @@ -286,6 +300,12 @@ export class TilingWindowManager {
>              );
>          }
>  
> +        if (window.override_constraints) {
> +            window.override_constraints(Meta.WindowConstraint.NONE,
> +                Meta.WindowConstraint.NONE, Meta.WindowConstraint.NONE,
> +                Meta.WindowConstraint.NONE);
> +        }
> +
>          // userOp means that the window won't clamp to the workspace. For DND
>          // we don't want to clamp to the workspace, so it's false by default.
>          const userOp = !clampToWorkspace;
> ```
> 
> Patch command if others want to try:
> 
> ```shell
> patch -p2 -d ~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/ < ~/Downloads/tilingWindowManager-Override-window-constraints-style.patch
> ```
> 
> Pulled from https://launchpad.net/ubuntu/+source/gnome-shell-extension-tiling-assistant.

What is the version of the GNOME that you are using? I tried to use the patch on Ubuntu 20.04 LTS with GNOME 3.36 and it seems that it requires GNOME 3.45 or higher.

**Comment by taisph** [comment]
> > FWIW, this is the patch they're using which makes the gaps disappear on my Ubuntu box. But it could very likely be something that only works on Ubuntu.
> > Pulled from https://launchpad.net/ubuntu/+source/gnome-shell-extension-tiling-assistant.
> 
> What is the version of the GNOME that you are using? I tried to use the patch on Ubuntu 20.04 LTS with GNOME 3.36 and it seems that it requires GNOME 3.45 or higher.

I believe the built in version was added in 23.04 or 23.10 and requires GNOME 3.44+.
