### ISSUE TITLE
Clicking the top bar un-maximizes window in Gnome 46

### ISSUE THREAD

**Issue by Anuskuss** [Leleat/Tiling-Assistant#327]
I have Chromium maximized and when I click on the top bar (i.e. right next to the tabs) the window becomes un-maximized. This gets really annoying because I usually click there when I want to give focus to that window.
So far I haven't found another application which exhibits that behaviour but I'm sure it's not strictly related to Chromium.

**Comment by taoky** [comment]
https://github.com/Leleat/Tiling-Assistant/blob/932846b0a3b852f8cf24b10d5de377726a31b33a/tiling-assistant%40leleat-on-github/src/extension/moveHandler.js#L141

```diff
- let cursorId = global.display.connect('cursor-updated', () => {
+ let cursorId = global.display.connect('grab-op-end', () => {
```

seems workarounds this issue, and also fixes the bug of clicking on *shell's* top bar could un-maximize current window.

Also Electron-based apps like VScode are affected by this issue. By reading mutter's source code it looks like `cursor-updated` signal would be used only when it is in X11 display.
