### ISSUE TITLE
Extension crashes (GLib.FileError: Failed to open file)

### ISSUE THREAD

**Issue by RouHim** [Leleat/Tiling-Assistant#341]
**Describe the bug**
I can not enable the extension

**Steps To Reproduce**
Install extensions, try to enable it

**System Info:**
 - Distro (incl. version): Arch
 - GNOME Shell version: 46.1
 - Extension version and from where (e. g. EGO, `main` branch...): v47, git version
 - XOrg/Wayland: wayland

**Journalctl logs**
`meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed`

**Screenshot**
![image](https://github.com/Leleat/Tiling-Assistant/assets/3582050/550f5b32-d079-4ecf-ba84-b65f995ef3e6)

**Comment by Leleat** [comment]
> Distro (incl. version): Arch
> GNOME Shell version: 46.1
> Extension version and from where (e. g. EGO, main branch...): v47, git version

Sine you are on Arch and the extension is installed as a 'system extension', I guess you are trying to install it from the AUR, right?

**Comment by RouHim** [comment]
Yes that's right.

**Comment by Leleat** [comment]
In that case this isn't really a bug on my end. So I am closing this issue.

I don't maintain the files needed for the AUR as I am not an Arch user.  Although I do have the 'versioned' files in the repo, they have been largely written by AUR users (and I do believe that the versioned AUR package should work). Looking at the git package it looks pretty unmaintained... my recommendation would be to try the versioned package, or install Tiling Assistant via [extensions.gnome.org](https://extensions.gnome.org/).
