### ISSUE TITLE
Ability to deactivate the complete assistant

### ISSUE THREAD

**Issue by Excel1** [Leleat/Tiling-Assistant#347]
**Briefly describe how the feature should work**
I want an option to deactivate the (system app) tiling assistant completely.

**Explain why this feature should be added**
Many users do not want to be patronised by system software. Some users want to use alternative tiling windows manager, which may conflict with this one.

**Comment by Leleat** [comment]
> Many users do not want to be patronised by system software. Some users want to use alternative tiling windows manager, which may conflict with this one.

I blieve you are misunderstanding what Tiling Assistant is.

Tiling Assistant isn't really 'system software'.  It's not a core part of your system or the GNOME desktop. It's a (community written) GNOME Shell extension that calls some API from GNOME's window manager/compositor to __add some window manager-ish features__. While your distro may ship it as as a 'System extension', you __can completely disable__ Tiling Assistant by disabling the extension in the `Extensions`  app, or with the `Extension Manager`, or however you manage your GNOME etxensions. Disabling Tiling Assistant however will not affect GNOME's existing window manager/compositor (Mutter). You will still keep the default 'floating window' behavior.
