### ISSUE TITLE
Window tiling like windows 11

### ISSUE THREAD

**Issue by Excel1** [Leleat/Tiling-Assistant#348]
**Briefly describe how the feature should work**
I wanna tile my windows like in windows 11.  Where i can navigate my windows everywhere with <super> + <arrow-key> like in 
https://github.com/Fmstrat/wintile (newer: https://github.com/GrylledCheez/wintile-beyond)

Currently i cant move the window to the bottom left corner just by using <super> + <arrow-key>

**Explain why this feature should be added**
It feels very comfortable to just use this combination of keys. As a user, I would also expect that if I can move my window to the upper left or right corner with <super> + <arrow-key>, I can also move it to the lower right/left corner. It also combines the features of the other specified plugins and you only need the tiling assistant

**Comment by Leleat** [comment]
> I wanna tile my windows like in windows 11. Where i can navigate my windows everywhere with + like in
https://github.com/Fmstrat/wintile (newer: https://github.com/GrylledCheez/wintile-beyond)

By '+' I guess, you mean to use the keyboard shortcuts  (like `Super`+`arrow keys`) used for tiling to move the window through the different tiling states. If so, that's already possible. You need to enable [this setting](https://github.com/Leleat/Tiling-Assistant/wiki/Dynamic-Keybindings#tiling-state). If that's not what you mean, please clarify.
