### ISSUE TITLE
Vertical/horizontal maximizing alters the other dimension

### ISSUE THREAD

**Issue by F-i-f** [Leleat/Tiling-Assistant#349]
**Describe the bug**
When maximizing horizontally, the vertical size shrinks.
When maximizing vertically, the horizontal size shrinks.

**Steps To Reproduce**
Maximize vertically or horizontally with Gaps set to 10.
Demo: 

https://github.com/Leleat/Tiling-Assistant/assets/17555212/e58032f0-6574-4ea5-a835-dcb9c7cd1c56

**System Info:**
 - Distro (incl. version): Fedora 40
 - GNOME Shell version: 46.2
 - Extension version and from where (e. g. EGO, `main` branch...): 47 from extensions.gnome.org.
 - XOrg/Wayland: Xorg

**Journalctl logs**
No messages are logged.

**Configuration**
```
$ dconf read /org/gnome/shell/enabled-extensions          
['tiling-assistant@leleat-on-github']
$ dconf dump /org/gnome/shell/extensions/tiling-assistant/
[/]
active-window-hint-color='rgb(53,132,228)'
enable-advanced-experimental-features=true
enable-tiling-popup=false
last-version-installed=47
maximize-with-gap=true
overridden-settings={'org.gnome.mutter.edge-tiling': <@mb nothing>}
restore-window=@as []
screen-bottom-gap=10
screen-left-gap=10
screen-right-gap=10
screen-top-gap=10
search-popup-layout=['<Super>semicolon']
show-layout-panel-indicator=false
tile-bottom-half=['<Super>period']
tile-bottomleft-quarter=['<Super>comma']
tile-bottomright-quarter=['<Super>slash']
tile-left-half=['<Super>l']
tile-maximize=['<Super>m']
tile-maximize-horizontally=['<Primary><Super>m']
tile-maximize-vertically=['<Shift><Super>m']
tile-right-half=['<Super>apostrophe']
tile-top-half=['<Super>bracketleft']
tile-topleft-quarter=['<Super>p']
tile-topright-quarter=['<Super>bracketright']
window-gap=10
```

**Comment by Leleat** [comment]
The (window) gaps are added to the window when it is maximized vertically/horizontally. It makes sense add the gaps if the window was already tiled. But I guess it is confusing, if the window is floating.

**Comment by Leleat** [comment]
I've opened #353 to fix it. Feel free to try it out and see if it's works as you expect it to.

**Comment by F-i-f** [comment]
Confirmed it works as expected now.
