### ISSUE TITLE
Tile to top is overridden by fullscreen Ubuntu 24.04

### ISSUE THREAD

**Issue by ajlamarc** [Leleat/Tiling-Assistant#358]
**Describe the bug**

When performing the "tile to top" action, I would expect the window to only cover the top half, but it jumps to fullscreen.  Note that "tile to top-left" does work as expected.

Apologies if this is a basic question :).  I fiddled with the settings for Tiling Assistant and tried following instructions [here](https://askubuntu.com/a/1510682) to fully remove the native Ubuntu tiling manager. However, the default "orange box" preview at the edge of the screen to snap to position still appears, which I'm guessing conflicts with this shortcut.

Thanks in advance for any suggestions!

**Steps To Reproduce**

With Tiling Assistant installed, perform the hotkey for "tile to top" on Ubuntu 24.04.

**System Info:**
 - Distro (incl. version): Ubuntu 24.04 LTS
 - GNOME Shell version: 46.0
 - Extension version and from where (e. g. EGO, `main` branch...): 47, from GNOME Shell Extensions
 - XOrg/Wayland: n/a

**Journalctl logs**
```
Can't update stage views actor unnamed [MetaWindowActorX11] is on because it needs an allocation.
Can't update stage views actor unnamed [MetaSurfaceActorX11] is on because it needs an allocation.
```

**Comment by Leleat** [comment]
Maybe whatever shortcut you've set for `tile to top` is already taken. Please check GNOME Settings to see if there are any conflicts. If you have other extensions installed, that might implement a 'fullscreen' shortcut, you should check them as well. Unfortunately, there isn't a (good) way to detect collisions for shortcuts in an extension.

**Comment by ajlamarc** [comment]
That seems to be it, `Super + Up` triggers fullscreen without the tiling assistant keybinding, and it works properly when I choose a different set of keys.

Thank you for the fast response and the awesome extension!
