### ISSUE TITLE
Can't set keybindings with Super key on GNOME 43.9

### ISSUE THREAD

**Issue by billbeans** [Leleat/Tiling-Assistant#366]
I'm trying to change the "Tile to bottom" keybinding to Super+Down so I can use the Tiling State behavior to tile my windows to the bottom left and right sections. I already changed the "Restore window size" binding to Alt+Down. Any time I try to set a keybinding to anything involving the Super key, nothing happens.

**Steps To Reproduce**
Open Extensions > Tiling Assistant > Settings > Keybindings > Tile to Bottom > try to set Super+Down

**System Info:**
 - Distro (incl. version): Debian GNU/Linux 12 (bookworm) x86_64
 - GNOME Shell version: GNOME Shell 43.9
 - Extension version and from where (e. g. EGO, `main` branch...):  Version 45 from the default Extension Manager in Debian Bookworm's repository
 - XOrg/Wayland: Wayland, or more specifically, Mutter

**Journalctl logs**

Nothing happens in the journalctl logs while I'm trying to set the keybinding

**Comment by Leleat** [comment]
I've installed Debian 12 in a VM and I can't reproduce this.

Did you make sure that also GNOME hasn't already registered a shortcut with `Super` + `Down` (i. e. check GNOME Settings). You may also need to check if other extensions already registered the shortcut (either by checking them manually or by just disabling them all to temporarily disable their shortcuts).

**Comment by billbeans** [comment]
> Did you make sure that also GNOME hasn't already registered a shortcut with Super + Down (i. e. check GNOME Settings).

No, I didn't think I had to. It is "Restore Window Size" by default, did you go into Settings and change that before reproducing? After changing the keybinding GNOME Settings, I was finally able to set the binding in the extension.

But now I can't change the "Restore Window Size" in the extension settings to match what I currently have it set to in GNOME Settings, even though certain other keybindings are shared between the two by default (Super+Left and Super+Right). To fix this, I had to unset the keybinding in GNOME Settings, set the keybinding in the extension settings, then reset the keybinding in GNOME Settings to have them shared.

This wasn't immediately obvious, but nevertheless, I have it set the way I want now. Thanks for helping and thanks for the great extension

**Comment by Leleat** [comment]
> But now I can't change the "Restore Window Size" in the extension settings to match what I currently have it set to in GNOME Settings, even though certain other keybindings are shared between the two by default (Super+Left and Super+Right). To fix this, I had to unset the keybinding in GNOME Settings, set the keybinding in the extension settings, then reset the keybinding in GNOME Settings to have them shared.

Maybe I misunderstood you, but to be certain: You shouldn't set the same keyboard shortcut in GNOME Settings and in Tiling Assistant. Only use the ones from Tiling Assistant (_or_ the ones from GNOME Settings). Having the same keyboard shortcut in GNOME Settings **and** Tiling Assistant may lead to undefined/unpredictable behavior.

**Comment by billbeans** [comment]
> Maybe I misunderstood you, but to be certain: You shouldn't set the same keyboard shortcut in GNOME Settings and in Tiling Assistant. Only use the ones from Tiling Assistant (or the ones from GNOME Settings). Having the same keyboard shortcut in GNOME Settings and Tiling Assistant may lead to undefined/unpredictable behavior.

Even if they do the same thing? Because by default the binding to "Restore Window Size" is Super+Down on GNOME, so just by installing the extension you have overlap

**Comment by Leleat** [comment]
> Even if they do the same thing?

While their name may suggest that the shortcuts do the same thing, they don't. GNOME's `Restore Window Size` only works on GNOME's natively tiledwindows, i. e. it generally won't work on windows tiled with Tiling Assistant (some exceptions like maximized windows exist). The reason is that GNOME isn't aware of the tiling states implemented by Tiling Assistant. Technically, windows tiled by Tiling Assistant still are just floating windows; they are just automatically positioned by Tiling Assistant for you.

That's why you should use the shortcuts from Tiling Asistant's settings for tiling etc. I am not sure what happens if you set Tiling Assistant's shortcuts to be the same as GNOME's native shortcuts but at best there is no negative effects, at worst you'll encounter bugs.

**Comment by billbeans** [comment]
> That's why you should use the shortcuts from Tiling Asistant's settings for tiling etc. I am not sure what happens if you set Tiling Assistant's shortcuts to be the same as GNOME's native shortcuts but at best there is no negative effects, at worst you'll encounter bugs.

Ok, that makes more sense. I just checked the GNOME keybinding settings and it seems like the bindings for Super+Left and Super+Right were silently disabled, as well as any others that were set by the extension. I didn't know this would happen either, which led to my confusion. I unset Restore Window Size for now, since Tiling Assistant already handles it
