### ISSUE TITLE
Invalid metadata in Polish translation

### ISSUE THREAD

**Issue by d235j** [Leleat/Tiling-Assistant#370]
**Describe the bug**

Compiling produces several warnings due to missing metadata in the Polish translation:
`CHARSET` at https://github.com/Leleat/Tiling-Assistant/commit/a3b47dbcbc3fd741af6c6fb4afe2416fab97b465#diff-41b44dae4b53deaec48bcca04948e0c5e4652f302e09edbb0710e1ce121a7ab3R17
This needs to be set to `UTF-8`.

`PACKAGE VERSION` also needs to be removed to prevent a warning.

**Steps To Reproduce**

Attempt building using the build script. Warnings will be produced.

**System Info:**

Arch Linux, latest versions as of now

**Comment by Leleat** [comment]
Weird, I do have a CI workflow that runs the build script and it did get the error of 

```
translations/pl.po: warning: Charset "CHARSET" is not a portable encoding name.
                             Message conversion to user's charset might not work.
translations/pl.po:8: warning: header field 'Project-Id-Version' still has the initial default value
translations/pl.po:8: warning: header field 'Content-Type' still has the initial default value
```

but the [CI still passed ](https://github.com/Leleat/Tiling-Assistant/actions/runs/10836702098/job/30071033880)for some reason... I'll need to investigate that.

Anyway, I opened an MR to adress this issue. Thanks for the report!
