### ISSUE TITLE
Move Mode Activator hotkey set to set to Alt is forgotten when activating the extension

### ISSUE THREAD

**Issue by normanr** [Leleat/Tiling-Assistant#374]
**Describe the bug**
 I find that my "Alt" Move Mode Activator hotkey is being reset every time my machine locks. "Ctrl", "RMB", "Super" are all preserved, just "Alt" is reset to "Disabled". I discovered this actually happens every time the extension is activated (when happens when unlocking), and can be reproduced by just disabling and enabling the extension.

**Steps To Reproduce**
Set "'Favourite Layout' Move Mode Activator" to Alt.
Either: Disable extension, enable extension (or: Lock screen with hotkey, or wait for it to timeout and auto-lock).

**System Info:**
 - Distro (incl. version): Debian testing
 - GNOME Shell version: Gnome 46.3.1
 - Extension version and from where (e. g. EGO, `main` branch...): EGO
 - XOrg/Wayland: X11

**Journalctl logs**
It doesn't matter what the hotkey setting is, the same entries are produced (in a different order each time):
```
Window manager warning: Overwriting existing binding of keysym ffb1 with keysym ffb1 (keycode 57).
Window manager warning: Overwriting existing binding of keysym ffb5 with keysym ffb5 (keycode 54).
Window manager warning: Overwriting existing binding of keysym ffb2 with keysym ffb2 (keycode 58).
Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
Window manager warning: Overwriting existing binding of keysym ffb3 with keysym ffb3 (keycode 59).
Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
Window manager warning: Overwriting existing binding of keysym ffb4 with keysym ffb4 (keycode 53).
Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Window manager warning: Overwriting existing binding of keysym ffb6 with keysym ffb6 (keycode 55).
Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Window manager warning: Overwriting existing binding of keysym ffb7 with keysym ffb7 (keycode 4f).
Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Window manager warning: Overwriting existing binding of keysym ffb8 with keysym ffb8 (keycode 50).
Window manager warning: Overwriting existing binding of keysym ffb9 with keysym ffb9 (keycode 51).
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
```

**Comment by Leleat** [comment]
Do you happen to have the `Window Action Key` set to `Alt`? You can get it by running 

```sh
gsettings get org.gnome.desktop.wm.preferences mouse-button-modifier
```

in a terminal.

**Comment by normanr** [comment]
I do:
```
$ gsettings get org.gnome.desktop.wm.preferences mouse-button-modifier
'<Alt>'
```
This worked in previous versions though (and it works until the extension is restarted).

**Comment by Leleat** [comment]
Ah, that's actually intentional then and not a bug. The fact that it "worked" previously was a bug because it may be confusing if you set a certain mode to `Alt` while also having the action key set to `Alt`. That means that you immediately enter that move mode  instead of the default (Edge Tiling) one, which may be confusing and has been reported as a bug [previously](https://github.com/Leleat/Tiling-Assistant/issues/313).

If you want to immediately enter a move mode, you can simply change the default move mode, no?

**Comment by normanr** [comment]
I don't want to immediately enter a move mode, most of the time I move windows using the title bar, so I generally don't hold Alt to initiate moving windows. When I do, it's okay that tiling mode is enabled, because I can immediately release Alt to get regular edge tiling (if I want), or continue to hold Alt if I want to use favorite layout.

Also I don't think there's a conflict with the window-move mouse-button-modifier. I can have both set to the same same key (temporarily) and it works correctly.

**Comment by Leleat** [comment]
> I don't want to immediately enter a move mode, most of the time I move windows using the title bar, so I generally don't hold Alt to initiate moving windows.

Sorry, but I don't think I will revert to the previous behavior. Implementing a feature in Tiling Assistant that directly conflicts with GNOME's native feature (i. e. moving windows with a modifier) and relies on needing to limit oneself to just move windows with the titlebar, sounds like a bad idea. While you may use the title bar to move windows, others may not.

If you really need access to all move modes via modifiers while being fine with a conflict with the `Windows Action Key`, you can comment out or delete the following lines: https://github.com/Leleat/Tiling-Assistant/blob/1c29ea09e815e266ddab6ff69f29a090c26cbfd4/tiling-assistant%40leleat-on-github/src/extension/moveHandler.js#L58-L72 from

```
~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/moveHandler.js
```

You will need to re-apply this change everytime, Tiling Assistant gets updated (which isn't that often). You can disable the updates by removing the `version` field from `~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/metadata.json`.

**Comment by normanr** [comment]
Thanks for the suggestions. I've ended up just switching to use a different modifier for GNOME's move window and Tiling Assistant's move mode activator. It's simpler and easier than having to manually maintain an edit to extension (and/or manually update it).
