### ISSUE TITLE
Active Window Hint settings missing since upgrade to F41 + GNOME 47

### ISSUE THREAD

**Issue by masterdokuro** [Leleat/Tiling-Assistant#380]
**Describe the bug**
After upgrading to fedora 41 which has gnome 47 the option for Active Window Hint no longer exists within this extensions settings.

**Steps To Reproduce**
Open up the settings for tiling assistant and scroll down the settings.  These options no longer exists.

BTW... I also tried removing the extension and reset its directory manually using dconf-editor (/org/gnome/shell/extensions/tiling-assistant, right click 'Reset recursively') and then reinstalled.  Did not bring back these settings.

**System Info:**
 - Distro: Fedora Linux 41 (Workstation Edition) x86_64
 - GNOME Shell version: GNOME 47.1
 - Extension version and from where (e. g. EGO, `main` branch...): https://extensions.gnome.org/extension/3733/tiling-assistant/
 - XOrg/Wayland: Wayland but also happens on X11

**Journalctl logs**
Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Error in size change accounting.
Error in size change accounting.

**Comment by Leleat** [comment]
I've [reworked the active window hint](https://github.com/Leleat/Tiling-Assistant/pull/344) and changed its behavior a bit. To distringuish it from the previous version, I've renamed it to "Focus Hint". Quoting from the pull request:

> This commits basically integrates https://github.com/Leleat/focus-indicator-prototype into Tiling Assistant. The other extension was just a prototype in cooperation with a GNOME Designer. But it is more polished than the active window hint that is currently in Tiling Assistant. I did some slight refactoring. I also removed the focus indication when using swipe gestures since the animation didn't work quite well (and had a bug during the animation with multiple monitors).
>
> This time however, the focus hint will be disabled by default as I don't believe it is that useful of a feature anymore, it deviates a bit too much from the stock GNOME behavior, and it may even be an unexpected behavior from a users perspective, if they don't know what it is or how it gets triggered. This is feature is also less tested as they are a lot of permutations of situations to test (multi-monitor, workspaces on all/primary display, etc).

**Comment by masterdokuro** [comment]
Very good, thank you.  I had not considered looking in the advanced settings.  I do like that outline and upscale have been separated within focus hint.
