### ISSUE TITLE
Tiling apps with multiple windows does not work in conjunction with AATWS (Advanced Alt-Tab Window Switcher) 

### ISSUE THREAD

**Issue by AlyMoh** [Leleat/Tiling-Assistant#381]
**Describe the bug**
When tiling a window, e.g. to the right, the app switcher is displayed on the left side. This works as well for an app that has multiple windows, e.g. two Firefox windows.

When Tiling Assistant is used alongside [AATWS](https://github.com/G-dH/advanced-alttab-window-switcher), this behaviour is broken; the app switcher is displayed, but the window switcher is no longer displayed, and thus I am unable to select which window should be tiled to the left.

This is not only restricted to the left tile; it applies to _any_ tiling.

**Steps To Reproduce**
1. Open two windows of an application and one window of another application. In the screencast below, I use GNOME Web and Warp with two and one windows open, respectively.
2. Snap the Warp window to the right.
3. The app switcher pop-up is displayed and works, but the window switcher is not displayed underneath the Web app, even through there are two windows to choose from.

https://github.com/user-attachments/assets/81e5870a-ea65-455f-b83f-bcfce65dba03

**System Info:**
 - Distro (incl. version): Fedora Linux 41 (Workstation Edition) x86_64
 - GNOME Shell version: 47.1
 - Extension version and from where (e. g. EGO, `main` branch...): GNOME Extensions
 - XOrg/Wayland: Wayland

**Journalctl logs**
No new entries are shown when the bug is reproduced, but the following were printed out after executing `journalctl -fo cat /usr/bin/gnome-shell`, probably before the bug is reproduced for the first time after boot.
```
fadeAndDestroy@file:///home/alymohamed/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingPopup.js:269:31
vfunc_key_press_event@resource:///org/gnome/shell/ui/switcherPopup.js:199:18
@resource:///org/gnome/shell/ui/init.js:21:20
```

If any further information is needed to help diagnose and solve this issue, please let me know! I already reported the bug on AATWS's repository.

Thank you for your time and help! :)

**Comment by Leleat** [comment]
Which version of AATWS are you using?

**Comment by G-dH** [comment]
The issue is that Tiling Assistant extends the `AppSwitcherPopup` class, which is already overridden by AATWS which functions differently from the default app switcher. I've only managed to handle the fatal errors caused by this conflict in AATWS.

**Comment by Leleat** [comment]
I am not familiar with AATWS feature set. Are there any feature in that that would

**Comment by Leleat** [comment]
Oops, sorry, send the post to early... I am gonna edit it.

**Comment by G-dH** [comment]
> I can just copy GNOME's entire code for the AppSwitcher into my extension rather than try to make both extensions compatible.

This is the way I would choose.

The main benefit of AATWS in this use case is its support for type-ahead search for both apps and windows, as well as its ability to launch new apps. However, it’s not worth the trouble.

**Comment by AlyMoh** [comment]
> Which version of AATWS are you using?

I am using the latest extension version from GNOME Extensions, namely version 59.
