### ISSUE TITLE
Tiling animations aren't displaying while another un/tiling animation is playing

### ISSUE THREAD

**Issue by Turbine1991** [Leleat/Tiling-Assistant#58]
Tile a window to the left of screen and then to the right, eventually the animations will be gone and it'll instantly maximize.

**Comment by Leleat** [comment]
I am not sure I can reproduce it. The only animation issue I have is when tiling via keybinding and tiling a window while the animation is still playing.
 
Do you have any clearer steps? Am I supposed to use the moues or keybindings? Am I supposed to use multiple apps and tile one of them using the tiling popup?...

**Comment by Turbine1991** [comment]
Have tiling dash disabled. It's easily reproducible.

On another note, are windows supposed to tile when the window touches the edge instead of the mouse? It's breaking proper windowing behaviour.

**Comment by Leleat** [comment]
> On another note, are windows supposed to tile when the window touches the edge instead of the mouse? It's breaking proper windowing behaviour.

No. I think you are still using the test version I created when testing touch a few days ago. There I tried to introduce window-position based tiling as a workaround (which didn't work). It should only happen on the right side and it's already removed from the current `master`.

**Comment by Leleat** [comment]
> Have tiling dash disabled. It's easily reproducible.

Could it be that the 'restore' animation is still playing when you do it (i. e. the fade out of the old window)?

**Comment by Leleat** [comment]
> Could it be that the 'restore' or another un/tiling animation is still playing when you do it (i. e. the fade out of the old window)?

Just gonna assume this is what you are talking about for now... since I can't (re)produce anything else.
