### ISSUE TITLE
.layouts.json stored in possibly non-writable extension directory.

### ISSUE THREAD

**Issue by apfelkuchen6** [Leleat/Tiling-Assistant#68]
**Describe the bug**
Tiling-Assistant fails to load the preferences when `.layouts.json` in the extension directory cannot be created because of insufficient permissions (for example when the extension is installed by the systems package manager)

**Steps To Reproduce**
Change the owner of the extension directory to someone else (root works fine), only grant yourself reading permissions (755 works), delete `.layout.json` and load the extension. Then open the settings panel of the extension and notice that it fails with
```
Gio.IOErrorEnum: Error opening file /etc/profiles/per-user/apfelkuchen6/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/.layouts.json: No such file or directory

Stack trace:
  _loadLayouts@/etc/profiles/per-user/apfelkuchen6/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/prefs.js:209:36
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
  _setupLayouts@/etc/profiles/per-user/apfelkuchen6/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/prefs.js:173:8
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
  _init@/etc/profiles/per-user/apfelkuchen6/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/prefs.js:59:8
  wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
  buildPrefsWidget@/etc/profiles/per-user/apfelkuchen6/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/prefs.js:29:17
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/nix/store/zahi11z0qcbk2yhwr221d9finagd3w13-gnome-shell-40.0/share/gnome-shell/.org.gnome.Shell.Extensions-wrapped:7:17
  

```

**System Info:** 
 - Distro: NixOS (current head of the gnome-40 branch) 
 - GNOME version: 40 
 - Extensions version: 8082b15706b83272da6a293287fda8de5bbc63d6
 - XOrg/Wayland: Wayland

**Journalctl logs**
I can't find anything related, it's probably not needed here though?

**Additional context**
I think the proper location for the config file would be `$XDG_CONFIG_HOME/tiling-assistant/layouts.json`. Alternatively storing everything in the gsettings store is an option.

Of course, when changing one would need to transition the old configs somehow.

**Comment by Leleat** [comment]
> I think the proper location for the config file would be $XDG_CONFIG_HOME/tiling-assistant/layouts.json. Alternatively storing everything in the gsettings store is an option.
> 
> Of course, when changing one would need to transition the old configs somehow.

I'll put the layouts file into your suggested location and write some code to copy the current layouts file to that location. Thanks for the feedback.

**Comment by Leleat** [comment]
Alright, implemented with the latest commit including compability code so that users won't notice it / don't have to recreate the layouts.

**Comment by apfelkuchen6** [comment]
Thanks a lot! It now works perfectly after manually creating the layouts file.
