### ISSUE TITLE
“Raise Windows When Focused” is not respected

### ISSUE THREAD

**Issue by randomizzerr** [Leleat/Tiling-Assistant#69]
**Describe the bug**
When ‘Window Focus’ is set to Focus on Hover and ‘Raise Windows When Focused’ is set to off within Gnome Tweaks, rather than only being raised on click, tilled windows are raised on hover when they're focused.

**Steps To Reproduce**
1. Tile a window.
2. Drag a floating window over the tiled window.
3. Hover the tiled window.

**Screenshots/-captures**
![Tiling](https://user-images.githubusercontent.com/67847243/116753786-a49fdb00-a9d5-11eb-866e-d6dfa8ec18d6.gif)

**System Info:**
 - Distro (incl. version): Manjaro 21.0.3
 - GNOME version: 40
 - Extensions version: 18
 - XOrg/Wayland: XOrg

**Journalctl logs**
No relevant logs are generated.

**Additional context**
This behaviour is only present with tiled windows. Floating windows and maximised windows behave normally.

**Comment by Leleat** [comment]
Thanks for the bug report. Can you test the current `master`? I should have it fixed now with the latest commit.

**Comment by randomizzerr** [comment]
Yep, that fixed it. Thanks!
