### ISSUE TITLE
How should an app be explicitly opened in a tiled state?

### ISSUE THREAD

**Issue by Leleat** [Leleat/Tiling-Assistant#70]
I've recently (re)added the ability to open apps in a tiled state by holding `Shift` when activating an app icon. This is hidden though. I didn't mention it anywhere and the relevant settings are in the *Hidden Settings* tab since I consider this feature **experimental**.

The most important code is the function [openAppTiled](https://github.com/Leleat/Tiling-Assistant/blob/b1171e9170f49b82abe9e8c004f8d3ed7d927a00/tiling-assistant%40leleat-on-github/tilingUtil.js#L605). It's kinda hacky and potentially unreliable... If someone has a better way, please open an issue/pr :)

Any way, this issue is actually about the behaviour and not the implementation. I'd like to hear people's opinion on how it should work.

---
**Goal**: Floating windows are and will always be the default behaviour. All tiling is exclusively initiated by the user. However, I do see the potential improvement, if apps can be immediately opend in a tiled state instead of having to open an app and then manually tiling it.

**Current State**: When activating an AppIcon (from the Dash, AppGrid and SearchResults) while holding `Shift`, a new window of that app will be opened in a tiled state. Possible tiled states:
1. if the free space created by the tiled windows is unambiguous (i. e. the free screen space consists of only 1 rectangle), the just-opened window willl fill that space.
2. if the focused window is tiled or maximized, halve the focused window and the just-opened window fills the other half. The direction and the spot the new window takes is indicated by a panel icon.
3. in all other cases the just-opened window will take half of the screen.

This feature is disabled by default in the *Hidden Settings* tab.

**Improvements**: I am not really happy with the inconsistency (i. e. having both case 1 and 2) or how you first need to press an additional shortcut to switch between horizontal/vertical tiling, but I am not sure how they could be unified... So any ideas? Feel free to also suggest something completely different from the current behaviour as long as the 'Goal' is met ;)

**Comment by laichiaheng** [comment]
holding Shift when activating an app icon never works.

**Comment by Leleat** [comment]
> holding Shift when activating an app icon never works.

Did you activate it in the hidden settings (it's experimental)

https://github.com/Leleat/Tiling-Assistant/blob/master/Guide.md#Hidden-Settings

How did you activate the app icon?

**Comment by laichiaheng** [comment]
@Leleat Thanks, it works.
I thought it would auto-tile all the windows.

**Comment by Leleat** [comment]
>  I thought it would auto-tile all the windows.

Sorry, I don't think I will ever implement that because I don't like tiling window managers.

**Comment by laichiaheng** [comment]
@Leleat Could the window size return to original size when the window is not tiled?

**Comment by Leleat** [comment]
> @Leleat Could the window size return to original size when the window is not tiled?

Sorry, I am not sure what you mean. The window size does return to its original size, if you untile it (by grabbing and moving the window around, if it's tiled or via keyboard shortcut. It's basically how it works with default with GNOME as well).

**Comment by laichiaheng** [comment]
> > @Leleat Could the window size return to original size when the window is not tiled?
> 
> Sorry, I am not sure what you mean. The window size does return to its original size, if you untile it (by grabbing and moving the window around, if it's tiled or via keyboard shortcut. It's basically how it works with default with GNOME as well).

With the experimental Semi Tiling mode, it doesn't.

**Comment by Leleat** [comment]
> With the experimental Semi Tiling mode, it doesn't. After I open the app with SHIFT key, it remains the size when I drag the window.

Does it happen for all windows or you happen to be on Wayland? It works for me

![output](https://user-images.githubusercontent.com/53054301/125162681-d0c79d00-e178-11eb-94a0-260f763f6666.gif)

**Comment by laichiaheng** [comment]
It also works for me now, I don't know what happened.

**Comment by TheRoarkster** [comment]
I wanted to add a thought here.  It seems (to me) that window tiling _should be_ integrated with automatic window movement (of some kind) on a per-app basis.  This seems to be one step beyond what you are going for, but I think it is in the same trajectory.  The result would be a holistic window tiling plugin that (1) controls keyboard and edging-based tiling and (2) allows users to set desired apps (and only those apps) to open in a specific tiled location (e.g., I always open terminal in the upper left quadrant and nautilus in the right half).   A plugin called "[Put Windows"](https://github.com/negesti/gnome-shell-extensions-negesti) is a good jumping off point for the second capability (it is currently not upgraded for GNOME 40).  

This is likely more than you were asking for, but given the invitation, I wanted to share the idea.

**Comment by Leleat** [comment]
Tbh, in the end I never used this feature and I am happy with where my extension currrently is... So I am closing this.

I don't even know, if anyone else actively uses this. So I am might remove it and see if anyone notices it being missing...
