### ISSUE TITLE
Dynamic layouts

### ISSUE THREAD

**Issue by Svadkos** [Leleat/Tiling-Assistant#73]
I don't know if it's out of scope, but can you add a stacked autotiling, where one window is a master and all other windows are stacked vertically or horizontally on a side of the master window. Then a new window can either be placed in the slave area, or replace a master window (old master goes to the slave area). Also, a slave can be promoted to a master.

**Comment by Leleat** [comment]
> I am gonna leave this issue open for now... maybe I am gonna add an option to automatically open windows tiled.

Nvm, closing this as I already had https://github.com/Leleat/Tiling-Assistant/issues/70 to track this feature.

**Comment by Svadkos** [comment]
I've seen this issue, and while that's a nice feature, it's not what I meant.

I meant something like layouts, which you show on the second gif. But instead of defining fixed layouts and assigning them to separate keys, you can press a button and currently focused window goes to the master area, all other windows automatically sent to a horizontal or vertical stack. When there are new floating windows in floating you can press the same button again and currently focused window, doesn't matter if it's floating or tiled, becomes a master and all other are auto stacked.

It's a basic form of course, there can be separate buttons for sending a focused window to stack or master area and leave all the other windows as they are. A button to change between vertical and horizontal mod. Windows in the stack can be ordered either automatically/randomly or manually by user (as it is now for layouts).

**Comment by Svadkos** [comment]
And it could be a solution to the problem that arise from implementing this https://github.com/Leleat/Tiling-Assistant/issues/70 
But alright, thank you for for this extension anyway.

**Comment by Leleat** [comment]
> ...

I see. That would make my extension a 'tiling window manager-ish' extension though, which makes the main feature (the Tiling popup) fairly useless. I am also personally not into tiling window managers, so I am not gonna add it.

**I'll reopen this though in case someone else wants to implement it. As long as it's optionally and doesn't touch the existing features, I'd merge a PR.**

**Comment by Svadkos** [comment]
BTW, maybe current layouts can be expanded a little bit to allow similar functionality while working with tiling popup.

Current format for layouts is `xVal--yVal--widthVal--heightVal` it allows only for fixed amount of windows in a layout, but a new key can be introduced, for example `Vtile` or just `V` for vertical and `H` for horizontal tiling, then no mutter how much windows are on a workspace they're all included in this layout, and you can choose which window goes where with tiling popup just like you do now with fixed layouts.

**Comment by Leleat** [comment]
Can you elobrate? If I am understanding you correctly, you mean something like this:

![Untitled](https://user-images.githubusercontent.com/53054301/117734479-13a1de80-b1e3-11eb-9e0b-b53d2cf09a78.png)

The black area is 1 rectangle for 1 window. The grey area would then be split up (vertically or horizontally) into equal parts based on the amount of remaining windows?

**Comment by Svadkos** [comment]
I think windows should fill the area, it's more in line with it's idea and it's more flexible, for example if you don't want all windows to be tiled.

**Comment by Leleat** [comment]
> I think windows should fill the area, it's more in line with it's idea and it's more flexible, for example if you don't want all windows to be tiled.

I've added an initial implementation to the `master` branch now. Can you test it and tell me what you think? I didn't limit it to 1 'dynamic' rectangle, you can use as many as you want. To use it append `--h` or `--v` to the `xVal--yVal--widthVal--heightVal` line. Pressing `Esc` with the 'dynamic' rectangle will jump to the next rectangle.

I don't know how to communicate to the user, in which direction the split happens. Any simple suggestions?

**Comment by Svadkos** [comment]
> Can you test it and tell me what you think?

Haven't tested it too much, but it seems good! Maybe an option to add gaps between windows in the dynamic area can be included? Like `--h0.01`. So it would look nice if a user has configured gaps between non-dynamic areas.

> I don't know how to communicate to the user, in which direction the split happens. Any simple suggestions?

Show where the new window will be placed with a blue rectangle, and fill the rest of the dynamic area with a color like gray. Don't know how simple it is to implement though.
It won't work for the first window in the area, but for that I can't think of any solution except drawing an arrow somewhere.

**Comment by Leleat** [comment]
> Haven't tested it too much, but it seems good! Maybe an option to add gaps between windows in the dynamic area can be included? Like --h0.01. So it would look nice if a user has configured gaps between non-dynamic areas.

There is already setting for gaps for all tiled windows. Why would you manually add gaps into the layout? (If you do that, you will mess with the tiling popup feature)

**Comment by Svadkos** [comment]
You're right, somehow it slipped.

**Comment by Leleat** [comment]
> Show where the new window will be placed with a blue rectangle, and fill the rest of the dynamic area with a color like gray. Don't know how simple it is to implement though.

Tried going with the dual color preview rectangles but I don't think it looked good cause you can see the other windows below it not fitting the preview rects. So I am just gonna leave it the way it is for now and hope most people don't care. I'll try to come up with something, if multiple people start mentioning it...

Anyway, closing this since it's now in `master` and I am not having any issues with it after some testing.

Thanks for the suggestion!

**Comment by Svadkos** [comment]
Thank you!

> you can see the other windows below it not fitting the preview rects.

For dynamic areas that preview would be a preview of a new state, so I think it doesn't matter much, and if it really look that bad maybe a more opaque whitish color can help?

**Comment by Leleat** [comment]
> For dynamic areas that preview would be a preview of a new state, so I think it doesn't matter much, and if it really look that bad maybe a more opaque whitish color can help?

I tried that but personally didn't like it or thought it was that useful. Here is a gif of it in action:

![output](https://user-images.githubusercontent.com/53054301/118129930-52ef4b80-b3ec-11eb-9882-2fec92c2b978.gif)

and screenshots for 2 and 3 windows with different colored backgrounds

![2](https://user-images.githubusercontent.com/53054301/118130020-6d292980-b3ec-11eb-96d6-344656d66011.png)

![3](https://user-images.githubusercontent.com/53054301/118130030-70bcb080-b3ec-11eb-8fbd-7173f4d97397.png)

**Comment by Svadkos** [comment]
I meant the reverse - blue for the new window and gray for remaining area, but still you're right, I forgot about white backgrounds.

Now that I think about it, maybe something like a wide blue line on the right/bottom border of the grayish opaque area would do better, and it won't clash with white and black window backgrounds that much.
