### ISSUE TITLE
Unexpected triggering by default moving with Shift+Arrows keybinding

### ISSUE THREAD

**Issue by l3nn4rt** [Leleat/Tiling-Assistant#76]
### Describe the bug

This extension is triggered when I try to move a window with default GS keybindings:
- Alt+F7 is for entering moving mode with the focused window;
- Shift+Arrows is for moving a window to the closest coordinates where one of its edges does overlap with another window edge or does touch the screen edge.

### Steps To Reproduce

1. Press Alt+F7 to enter window moving mode
2. Press Shift+ARROW where ARROW is any arrow key
3. Press Enter to confirm position, or Esc to return to original one
    - No matter what you do here, TilingAssistant will do tile window in the top-left corner

### Screenshots/-captures

https://streamable.com/plih19

### System Info:
 - Distro (incl. version): Arch Linux
 - GNOME version: 40.1
 - Extensions version: 20
 - XOrg/Wayland: Wayland

**Journalctl logs**

```
Error in size change accounting.
```

**Comment by l3nn4rt** [comment]
I think tiling should not be triggered at all, since we use `Alt`+`F7` to change window position, while leaving its shape unmodified.
Also, I just noticed this happens without `Shift` too (i.e. pressing `Alt`+`F7` and then moving with arrows).

Maybe the tiling function could be triggered if an additional modifier is used with arrows (or `Shift`+arrows), e.g. if we press `Alt`+`F7` and then `Ctrl`+arrows (or `Ctrl`+`Shift`+arrows), but, IMHO, default moving mode should be preserved.

**Comment by Leleat** [comment]
Pushed new commit to fix the bug. The tiling preview will be shown based on the pointer position.

> Maybe the tiling function could be triggered if an additional modifier is used with arrows

I didn't put the window movement with `Alt` + `F7` behind a modifier for now. If you can, please test it and see how you feel about it. Reason is that `Alt` + `F7` + `Mouse` movement would also be affected because I can't differentiate it from `Alt` + `F7` + `Arrow` keys.

**Comment by l3nn4rt** [comment]
Well, it's no more overriding default `Alt`+`F7` which is perfect! :100: 
Thank you so much!
