### ISSUE TITLE
Can't setup layouts

### ISSUE THREAD

**Issue by shdwchn10** [Leleat/Tiling-Assistant#77]
**Describe the bug**
When I enter layouts settings I can't type anything in text inputs.

**Steps To Reproduce**
Just open layout settings

**Screenshots/-captures**

https://user-images.githubusercontent.com/79763381/121765923-eb890080-cb3d-11eb-8509-0a9b3b89e9ec.mp4

**System Info:**
 - Distro (incl. version): Fedora Silverblue 34
 - GNOME version: 40.1
 - Extensions version: 20
 - XOrg/Wayland: Wayland

**Journalctl logs**
No journal entries when reproducing

**Comment by Leleat** [comment]
It's already fixed in `master`. Pushed a new version (v21) to EGO just now. Give it a few hours/days and it should be up.
