### ISSUE TITLE
requestPictureInPicture issue

### ISSUE THREAD

**Issue by Defatul** [Leleat/Tiling-Assistant#79]
https://user-images.githubusercontent.com/10219137/123498467-bb128d80-d638-11eb-8608-64f99b63d564.mp4

**Comment by Leleat** [comment]
Can you please provide more details? What's exactly is the issue?

Is it that the PiP window above everything else? Or is it that the Tiling Popup still appears? Or something completely different?

**Comment by Leleat** [comment]
Closing due a lack of repsonse. My questions remain. What's exactly is the issue and what's the expected behaviour...?

> Is it that the PiP window is above everything else? Or is it that the Tiling Popup still appears? Or something completely different?
