### ISSUE TITLE
Error updating extension

### ISSUE THREAD

**Issue by d3v0m4r** [Leleat/Tiling-Assistant#82]
After updating the extension it gives an error and stops working
I am using ubuntu 20.04 with gnome 3.36.8
![2021-07-02 15 38 42 extensions gnome org 8baf1a444ca0](https://user-images.githubusercontent.com/35973167/124321384-97c17400-db4b-11eb-9bfb-2607db5da5f4.png)

**Comment by Leleat** [comment]
I've tested it in a VM with Ubuntu 20.04 and GNOME 3.36. I didn't get an error. It's possibly just a borked update process. Try reloading GNOME Shell (X11: Alt+F2 -> r; Wayland: logout and back in).

**Comment by d3v0m4r** [comment]
> I've tested it in a VM with Ubuntu 20.04 and GNOME 3.36. I didn't get an error. It's possibly just a borked update process. Try reloading GNOME Shell (X11: Alt+F2 -> r; Wayland: logout and back in).

Yes it's correct
You were right, i did alt + f2 -> r
And now it works fine
Thank you so much
