### ISSUE TITLE
How to disable a keybinding

### ISSUE THREAD

**Issue by Master811129** [Leleat/Tiling-Assistant#83]
How set a keybinding entry to disabled? 

![image](https://user-images.githubusercontent.com/37829730/124363292-a002d780-dc4f-11eb-9396-e4a9f80a0fde.png)

**Comment by Leleat** [comment]
> How set a keybinding entry to disabled?

Double click the shortcut and hit backspace (this is GNOME/GTK's default behaviour).

**Comment by Master811129** [comment]
> > How set a keybinding entry to disabled?
> 
> Double click the shortcut and hit backspace (this is GNOME/GTK's default behaviour).

Thanks man. I appreciate your help.
