### ISSUE TITLE
Double click to maximize doesn't have a gap.

### ISSUE THREAD

**Issue by PizzaLovingNerd** [Leleat/Tiling-Assistant#86]
**Describe the bug**
Double click to minimize makes the gap go away.

**Steps To Reproduce**
Toggle the extension on, enable window gaps and enable gaps on maximized windows, than double click a window to maximize.

**Screenshots/-captures**
https://youtu.be/TaecuuwlMYw

**System Info:**
 - Distro: Fedora 34
 - GNOME version: 40.1

 - Extensions version: 22
 - XOrg/Wayland: Xorg

**Journalctl logs**
No output.

**Comment by Leleat** [comment]
Unfortunately, I don't think there is anything I can do about it as a GNOME Shell extension, because that is handled in mutter. Same probably applies to the `Maximize Button` (if it is enabled).

So I am gonna close this and put it under the the known limitations.
