### ISSUE TITLE
Extension displays Error in Gnome Extensions list after recent update

### ISSUE THREAD

**Issue by Digitale-Substanz** [Leleat/Tiling-Assistant#88]
![scrnsht-tiling-assistant](https://user-images.githubusercontent.com/8035912/127963836-911db1a0-7ef4-48ad-9b00-5ec574645bd7.png)
**Describe the bug**
When starting my computer today, a Gnome message asked me to update the Tiling-Assistant extension. After trying to do, the extension is no longer working. Instead, there's an "Error" label now in Gnome extensions list (see screenshot attached).

**Steps To Reproduce**
1. Start system an log into user profile
2. Open https://extensions.gnome.org/local/
3. Detect 'Update' sign on Tiling-Assistant extension (green gear)
4. Push update sign button
5. Receive 'Error' sign. 

**Screenshots/-captures**
See image.

**System Info:**
 - Distro (incl. version): Ubuntu 20.04
 - GNOME version: 3.36.8
 - Extensions version: 23
 - XOrg/Wayland: X11

**Journalctl logs**

**Additional context**

**Comment by ma44in** [comment]
Moin Digitale-Substanz

If you click on the error sign you should get a detailed message. In my case the error message suggested to logout and login again. 

So in any case you could try to logout and login.

**Comment by Leleat** [comment]
I've tested the extension in a VM with Ubuntu 20.04 and I am not getting any errors.

As ma44in suggested, try restarting GNOME Shell (on Wayland: re-login; on X11: Alt+F2 -> 'r' is enough). For some reason the update process doesn't work properly sometimes... If that doesn't fix it, please report back here.
