### ISSUE TITLE
Additional tiling hotkey options. In particular, toggleable RMB.

### ISSUE THREAD

**Issue by NotChristianGarcia** [Leleat/Tiling-Assistant#90]
**Feature Request**
I believe it would be greatly beneficial to allow users to change the `ctrl` key to start tiling (Or allow `ctrl` and another key). The most useful of these choice being the `RMB`. This would allow a completely mouse based system of tiling, abandoning use of the keyboard when moving windows around in whatever layout.

**Additional context**
This feature would get Tiling Assistant to the level of Window's Fancy Zones to be honest, something I've grown extremely fond of. This is mainly for desktop usage, as `ctrl` works very well for touch pads, but is pretty unnecessary when using a mouse. The ability to drag a window and start tiling while holding the `RMB` would be great, but while you're at it, if you also wanted to make it a toggleable feature, that would be ++ in the sense that you just transition into "tiling mode" with the click.

Might be impossible! But it might just be a quick change. I really appreciate tiling assistant for being one of very few sane tiling managers, thanks for all your work!

**Comment by Leleat** [comment]
I've added it to `master` as [Hidden Settings](https://github.com/Leleat/Tiling-Assistant/blob/master/GUIDE.md#Hidden-Settings) (called `Tile Preview: Default to Secondary Mode` and `Tile Preview: Secondary Mode Activator`). Please test it and tell me what you think. Not sure, if using `RMB` works properly. It works on my desktop but not in a VM... no idea why...

**Comment by NotChristianGarcia** [comment]
Hello again!

I absolutely love `Default to Secondary Mode`, works as expected. Thanks for that.
`Secondary Mode Activator` works well for me with both `ctrl` and `alt`, not `RMB` though unfortunately. Ubuntu 20.04, tried Wayland and X. Using a bluetooth mouse and touchpad, no go either way. Let me know if I can help!

**Comment by Leleat** [comment]
> It works on my desktop but not in a VM... no idea why...

My previous statement was wrong. It wasn't because I was in a VM but because I was on Wayland. There is a bug in Clutter on Wayland about wrong button masks (https://gitlab.gnome.org/GNOME/clutter/-/merge_requests/15). On Wayland it should work with `MMB`. 

> Ubuntu 20.04, tried Wayland and X

This however I can't explain. Could you please explain step-by-step what you did (grabbed the titlebar, etc. ?)? I've tested on Ubuntu 20.4 (in the VM) and it worked there except for the issue with `RMB` and `MMB` mentioned above.

**Comment by NotChristianGarcia** [comment]
Everything's working! Was initially on Wayland and I guess I just failed to switch to X properly. Everything works as you described, `MMB` in Wayland and `RMB` in X. Awesome.

Thank you very much!
