### ISSUE TITLE
A way how to restore default keybindings or disable them

### ISSUE THREAD

**Issue by denis-khizhniak** [Leleat/Tiling-Assistant#97]
Please tell me the way how to restore default keybindings or disable them. It would be helpful to add this to the documentation.

**Comment by Leleat** [comment]
double click on the shortcut (it will listen for a new shortcut) and press `Backspace`. 

FYI, this is how it's done in GNOME/GTK as well (and other apps etc). But I guess I need to add a GUI option since I've been asked this a few times already ^^'
