### ISSUE TITLE
Want to disable a keyboard shortcut

### ISSUE THREAD

**Issue by ethanbowering24** [Leleat/Tiling-Assistant#99]
I was tinkering and set a keyboard shortcut in the extensions settings. I can't figure out how to return it to "Disabled". I have uninstalled the extension, removed ~/.config/tiling-assistant but it always comes back. Help is appreciated.

**Comment by Leleat** [comment]
double click on the shortcut (it will listen for a new shortcut) and press Backspace.

FYI, this is how it's done in GNOME/GTK as well (and other apps etc). In `master` I've added a way to do it via GUI (still need to push it to EGO).

**Comment by ethanbowering24** [comment]
> double click on the shortcut (it will listen for a new shortcut) and press Backspace.
> 
> FYI, this is how it's done in GNOME/GTK as well (and in a lot of other apps etc). In `master` I've added a way to do it via GUI (still need to push it to EGO).

Wow I am silly. I swore I tried that. Thanks!
